// Module registry (Phase 7): the single source for module identity, navigation and authority.
// Data is generated by python/module_registry.py into src/generated/moduleRegistry{,Core}.ts and
// moduleRegistry.json; edit the Python registry and regenerate (`python -m module_contract emit` from python/).
//
// Only the small core slice (navigation identity, maturity, evidence ceiling, oracle state) is bundled
// eagerly. Full contracts (operations, fields, notes, source refs) are loaded on demand through
// loadModuleContractDetails(), so they stay out of the entry chunk.
import { MODULE_REGISTRY_CORE } from '../generated/moduleRegistryCore';

export * from '../generated/moduleRegistryCore';
export type {
  AuthorityKind, BackgroundWork, ContractAuthority, ContractField, ContractOperation, ContractValidityDomain,
  FieldValueType, ForbiddenClaimKey, GpuMode, LifecycleResource, ModuleContract, ModuleRegistryDocument,
} from '../generated/moduleRegistry';

export type RegisteredContract = typeof MODULE_REGISTRY_CORE.contracts[number];
export type RegisteredModuleId = RegisteredContract['id'];
/** Contracts shown in navigation; hidden contracts stay registered but unlisted. */
export type ListedContract = Extract<RegisteredContract, { readonly navigation: 'listed' }>;
export type ListedModuleId = ListedContract['id'];

export const MODULE_CONTRACTS: readonly RegisteredContract[] = MODULE_REGISTRY_CORE.contracts;

function isListed(contract: RegisteredContract): contract is ListedContract {
  return contract.navigation === 'listed';
}

/** Listed contracts in registry order (the navigation order). */
export const LISTED_CONTRACTS: readonly ListedContract[] = MODULE_REGISTRY_CORE.contracts.filter(isListed);

export function contractById(id: string): RegisteredContract | undefined {
  return MODULE_CONTRACTS.find(contract => contract.id === id);
}

/** Full registry document (dynamic import; a separate chunk). */
export function loadModuleContractDetails() {
  return import('../generated/moduleRegistry').then(module => module.MODULE_REGISTRY);
}
