// Module registry (Phase 7): the single source for module identity, navigation and authority.
// Data is generated by python/module_registry.py into src/generated/moduleRegistry.{json,ts};
// edit the Python registry and regenerate (`python -m module_contract emit` from python/).
import { MODULE_REGISTRY } from '../generated/moduleRegistry';

export * from '../generated/moduleRegistry';

export type RegisteredContract = typeof MODULE_REGISTRY.contracts[number];
export type RegisteredModuleId = RegisteredContract['id'];
/** Contracts shown in navigation; hidden contracts stay registered but unlisted. */
export type ListedContract = Extract<RegisteredContract, { readonly navigation: 'listed' }>;
export type ListedModuleId = ListedContract['id'];

export const MODULE_CONTRACTS: readonly RegisteredContract[] = MODULE_REGISTRY.contracts;

function isListed(contract: RegisteredContract): contract is ListedContract {
  return contract.navigation === 'listed';
}

/** Listed contracts in registry order (the navigation order). */
export const LISTED_CONTRACTS: readonly ListedContract[] = MODULE_REGISTRY.contracts.filter(isListed);

export function contractById(id: string): RegisteredContract | undefined {
  return MODULE_CONTRACTS.find(contract => contract.id === id);
}
