import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { computeAerospaceScreeningStats } from "../src/utils/aerospaceScreening";
import { computeQualificationMmpdsStats } from "../src/utils/qualificationScreening";
import { natrellaOneSidedToleranceFactor, screeningToleranceFactors } from "../src/utils/toleranceFactors";

// Independent oracle: EXACT one-sided normal tolerance factors k = nct.ppf(0.95, N-1, z_p sqrt(N)) / sqrt(N)
// for N = 5..300, generated by tests/fixtures/one_sided_tolerance_factor_oracle.py (scipy 1.15.3) and cross-checked
// there against a chi-square quadrature of the same coverage probability (|diff| <= 1e-6).
interface OracleRow {
  N: number;
  kA: number;
  kB: number;
}
const oracle: { rows: OracleRow[] } = JSON.parse(
  readFileSync(new URL("./fixtures/one-sided-tolerance-factor-oracle.json", import.meta.url), "utf8")
);
const exact = new Map(oracle.rows.map((r) => [r.N, r]));

const Z99 = 2.326348;
const Z90 = 1.281552;
const ZG = 1.644854;

// Spot values from the generated table (also the commonly tabulated one-sided factors, e.g. N=10: 3.981 / 2.355).
test("oracle table sanity: spot values and monotone decrease towards z_p", () => {
  assert.equal(oracle.rows.length, 296);
  assert.deepEqual([exact.get(10)!.kA, exact.get(10)!.kB], [3.981118, 2.35464]);
  assert.deepEqual([exact.get(60)!.kA, exact.get(60)!.kB], [2.807055, 1.608913]);
  for (let N = 6; N <= 300; N++) {
    assert.ok(exact.get(N)!.kA < exact.get(N - 1)!.kA && exact.get(N)!.kA > Z99);
    assert.ok(exact.get(N)!.kB < exact.get(N - 1)!.kB && exact.get(N)!.kB > Z90);
  }
});

// First-principles derivation of the closed form: the lower bound xbar - k s is treated as normal with mean
// mu - k sigma and variance sigma^2 (1/N + k^2 / (2(N-1))). Requiring it to fall below mu - z_p sigma with
// probability gamma gives (k - z_p)^2 = z_g^2 (1/N + k^2/(2(N-1))), i.e. a k^2 - 2 z_p k + b = 0 with
// a = 1 - z_g^2/(2(N-1)), b = z_p^2 - z_g^2/N, whose larger root is k = (z_p + sqrt(z_p^2 - a b)) / a.
test("shared k is the larger root of the Natrella quadratic a k^2 - 2 z_p k + b = 0 (to display rounding)", () => {
  for (let N = 10; N <= 300; N++) {
    const a = 1 - (ZG * ZG) / (2 * (N - 1));
    for (const z of [Z99, Z90]) {
      const b = z * z - (ZG * ZG) / N;
      // roots of the quadratic, found here by the textbook formula 2a k = 2 z_p +- sqrt(4 z_p^2 - 4 a b)
      const disc = 4 * z * z - 4 * a * b;
      const root = (2 * z + Math.sqrt(disc)) / (2 * a);
      assert.ok(Math.abs(a * root * root - 2 * z * root + b) < 1e-12, `root check N=${N}`);
      const k = natrellaOneSidedToleranceFactor(z, N);
      assert.ok(Math.abs(k - root) <= 0.0005 + 1e-12, `N=${N} z=${z}: ${k} vs ${root}`);
    }
  }
});

test("shared k tracks the exact non-central-t factor: <= 1.5 % low for N >= 10, <= 1 % for N >= 16, error shrinking", () => {
  let prevA = Infinity;
  let prevB = Infinity;
  for (let N = 10; N <= 300; N++) {
    const { kA, kB } = screeningToleranceFactors(N);
    const e = exact.get(N)!;
    const relA = (kA - e.kA) / e.kA;
    const relB = (kB - e.kB) / e.kB;
    // The approximation is never above the exact value here (slightly optimistic) ...
    assert.ok(relA <= 0 && relB <= 0, `N=${N}`);
    // ... by at most 1.04 % (A) / 1.43 % (B), at N = 10.
    assert.ok(relA >= -0.0104 && relB >= -0.0143, `N=${N}: A ${relA} B ${relB}`);
    if (N >= 11) assert.ok(kA >= e.kA * 0.99, `A N=${N}`);
    if (N >= 16) assert.ok(kB >= e.kB * 0.99, `B N=${N}`);
    // |error| decreases with N (allow display-rounding jitter: two roundings to 0.001)
    assert.ok(-relA <= prevA + 0.001 / kA && -relB <= prevB + 0.001 / kB, `N=${N}`);
    prevA = -relA;
    prevB = -relB;
  }
});

test("both screens use the same k (qualification == aerospace, bit for bit)", () => {
  for (let N = -5; N <= 600; N++) {
    const q = computeQualificationMmpdsStats({
      meanYieldMpa: 930,
      meanTensileMpa: 1010,
      fractureToughnessMpaM: 68,
      sampleSizeN: N,
      customScatterCv: 2.8,
    });
    const a = computeAerospaceScreeningStats({ meanYieldMpa: 930, meanTensileMpa: 1010, sampleSizeN: N, scatterCvPct: 2.8 });
    assert.ok(Object.is(q.kA, a.kA) && Object.is(q.kB, a.kB), `N=${N}`);
  }
});

// ---------------------------------------------------------------------------------------------------------------
// HISTORICAL (bug fixed 2026-10): StandardQualificationEngine used k = z_p + sqrt(z_p^2 - a b) / a (the division
// bound only to the sqrt). Re-implemented here verbatim so the delta stays visible to reviewers.
// ---------------------------------------------------------------------------------------------------------------
function oldMisgroupedK(z: number, N: number): number {
  return Number(
    (z + Math.sqrt(z * z - (1 - (ZG * ZG) / (2 * (N - 1))) * (z * z - (ZG * ZG) / N)) / (1 - (ZG * ZG) / (2 * (N - 1)))).toFixed(3)
  );
}

test("HISTORICAL old qualification k: pinned values, optimistic against the exact factor at every N", () => {
  const pinned = Object.fromEntries([10, 30, 60, 100].map((N) => [N, [oldMisgroupedK(Z99, N), oldMisgroupedK(Z90, N)]]));
  assert.deepEqual(pinned, { 10: [3.528, 2.094], 30: [2.937, 1.705], 60: [2.746, 1.574], 100: [2.648, 1.506] });
  for (let N = 10; N <= 300; N++) {
    const e = exact.get(N)!;
    const fixed = screeningToleranceFactors(N);
    assert.ok(oldMisgroupedK(Z99, N) < e.kA && oldMisgroupedK(Z90, N) < e.kB, `N=${N}`);
    // the old value is further from the exact factor than the fixed one at every N
    assert.ok(e.kA - oldMisgroupedK(Z99, N) > e.kA - fixed.kA, `A N=${N}`);
    assert.ok(e.kB - oldMisgroupedK(Z90, N) > e.kB - fixed.kB, `B N=${N}`);
  }
  // at N = 10 the old k was 11.4 % (A) / 11.1 % (B) below exact
  assert.ok((exact.get(10)!.kA - 3.528) / exact.get(10)!.kA > 0.11);
  assert.ok((exact.get(10)!.kB - 2.094) / exact.get(10)!.kB > 0.11);
});
