import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { computeAerospaceScreeningStats } from "../src/utils/aerospaceScreening";
import { computeQualificationMmpdsStats } from "../src/utils/qualificationScreening";
import { EXACT_K_A, EXACT_K_B, EXACT_K_FIRST_N, EXACT_K_LAST_N } from "../src/utils/toleranceFactorTable";
import { natrellaOneSidedToleranceFactor, screeningToleranceFactors, toleranceFactorMethodLabel } from "../src/utils/toleranceFactors";

// Independent oracle: EXACT one-sided normal tolerance factors k = nct.ppf(0.95, N-1, z_p sqrt(N)) / sqrt(N)
// for N = 5..300, generated by tests/fixtures/one_sided_tolerance_factor_oracle.py (scipy 1.15.3) and cross-checked
// there against a chi-square quadrature of the same coverage probability (|diff| <= 1e-6).
interface OracleRow {
  N: number;
  kA: number;
  kB: number;
}
const oracle: { rows: OracleRow[] } = JSON.parse(
  readFileSync(new URL("./fixtures/one-sided-tolerance-factor-oracle.json", import.meta.url), "utf8")
);
const exact = new Map(oracle.rows.map((r) => [r.N, r]));

const Z99 = 2.326348;
const Z90 = 1.281552;
const ZG = 1.644854;

// Spot values from the generated table (also the commonly tabulated one-sided factors, e.g. N=10: 3.981 / 2.355).
test("oracle table sanity: spot values and monotone decrease towards z_p", () => {
  assert.equal(oracle.rows.length, 296);
  assert.deepEqual([exact.get(10)!.kA, exact.get(10)!.kB], [3.981118, 2.35464]);
  assert.deepEqual([exact.get(60)!.kA, exact.get(60)!.kB], [2.807055, 1.608913]);
  for (let N = 6; N <= 300; N++) {
    assert.ok(exact.get(N)!.kA < exact.get(N - 1)!.kA && exact.get(N)!.kA > Z99);
    assert.ok(exact.get(N)!.kB < exact.get(N - 1)!.kB && exact.get(N)!.kB > Z90);
  }
});

test("the embedded TypeScript table is the oracle JSON verbatim (generated by the committed script --emit-ts)", () => {
  assert.equal(EXACT_K_FIRST_N, 5);
  assert.equal(EXACT_K_LAST_N, 300);
  assert.equal(EXACT_K_A.length, oracle.rows.length);
  assert.equal(EXACT_K_B.length, oracle.rows.length);
  oracle.rows.forEach((r, i) => {
    assert.equal(r.N, EXACT_K_FIRST_N + i);
    assert.equal(EXACT_K_A[i], r.kA);
    assert.equal(EXACT_K_B[i], r.kB);
  });
});

test("for 5 <= N <= 300 the shared k is the exact factor rounded UP to 3 decimals (never optimistic)", () => {
  for (let N = 5; N <= 300; N++) {
    const { kA, kB } = screeningToleranceFactors(N);
    const e = exact.get(N)!;
    assert.ok(kA >= e.kA && kA - e.kA < 0.001, `A N=${N}: ${kA} vs ${e.kA}`);
    assert.ok(kB >= e.kB && kB - e.kB < 0.001, `B N=${N}: ${kB} vs ${e.kB}`);
  }
  assert.deepEqual(screeningToleranceFactors(10), { kA: 3.982, kB: 2.355 });
  assert.deepEqual(screeningToleranceFactors(60), { kA: 2.808, kB: 1.609 });
  // a non-integer N uses floor(N): fewer coupons, larger k
  assert.deepEqual(screeningToleranceFactors(12.7), screeningToleranceFactors(12));
});

test("the exact-table k is never below the Natrella k for N in 10..300 (switching to it can only be conservative)", () => {
  for (let N = 10; N <= 300; N++) {
    const t = screeningToleranceFactors(N);
    assert.ok(t.kA >= natrellaOneSidedToleranceFactor(Z99, N), `A N=${N}`);
    assert.ok(t.kB >= natrellaOneSidedToleranceFactor(Z90, N), `B N=${N}`);
  }
});

test("continuity: k is non-increasing in N across N = 30/31 and across the table end N = 300/301", () => {
  let prev = screeningToleranceFactors(10);
  for (let N = 11; N <= 1000; N++) {
    const cur = screeningToleranceFactors(N);
    assert.ok(cur.kA <= prev.kA && cur.kB <= prev.kB, `N=${N}`);
    prev = cur;
  }
  const k30 = screeningToleranceFactors(30);
  const k31 = screeningToleranceFactors(31);
  assert.deepEqual([k30, k31], [{ kA: 3.064, kB: 1.778 }, { kA: 3.049, kB: 1.768 }]);
  const k300 = screeningToleranceFactors(300);
  const k301 = screeningToleranceFactors(301);
  // at the switch to Natrella the step (2.522 -> 2.520, 1.417 -> 1.416) is at most 0.002: round-up of the table
  // value (< 0.001) + Natrella shortfall at N~300 (< 0.1 %, ~0.0009 for A) + its own rounding (0.0005)
  assert.deepEqual([k300, k301], [{ kA: 2.522, kB: 1.417 }, { kA: 2.52, kB: 1.416 }]);
  assert.ok(k300.kA - k301.kA <= 0.002 + 1e-12 && k300.kB - k301.kB <= 0.002 + 1e-12);
});

// First-principles derivation of the closed form used above the table: the lower bound xbar - k s is treated as
// normal with mean mu - k sigma and variance sigma^2 (1/N + k^2 / (2(N-1))). Requiring it to fall below
// mu - z_p sigma with probability gamma gives (k - z_p)^2 = z_g^2 (1/N + k^2/(2(N-1))), i.e. a k^2 - 2 z_p k + b = 0
// with a = 1 - z_g^2/(2(N-1)), b = z_p^2 - z_g^2/N, whose larger root is k = (z_p + sqrt(z_p^2 - a b)) / a.
test("Natrella k is the larger root of a k^2 - 2 z_p k + b = 0 (to display rounding)", () => {
  for (let N = 10; N <= 1000; N++) {
    const a = 1 - (ZG * ZG) / (2 * (N - 1));
    for (const z of [Z99, Z90]) {
      const b = z * z - (ZG * ZG) / N;
      // roots of the quadratic, found here by the textbook formula 2a k = 2 z_p +- sqrt(4 z_p^2 - 4 a b)
      const disc = 4 * z * z - 4 * a * b;
      const root = (2 * z + Math.sqrt(disc)) / (2 * a);
      assert.ok(Math.abs(a * root * root - 2 * z * root + b) < 1e-12, `root check N=${N}`);
      const k = natrellaOneSidedToleranceFactor(z, N);
      assert.ok(Math.abs(k - root) <= 0.0005 + 1e-12, `N=${N} z=${z}: ${k} vs ${root}`);
    }
  }
});

test("Natrella error vs exact (why the table covers N <= 300): 1.04/1.43 % low at N=10, 0.44/0.53 % at N=31, <0.1 % at N=300", () => {
  const rel = (z: number, key: "kA" | "kB", N: number) => (natrellaOneSidedToleranceFactor(z, N) - exact.get(N)![key]) / exact.get(N)![key];
  for (let N = 10; N <= 300; N++) assert.ok(rel(Z99, "kA", N) <= 0 && rel(Z90, "kB", N) <= 0, `N=${N}`);
  assert.ok(rel(Z99, "kA", 10) < -0.0103 && rel(Z90, "kB", 10) < -0.0142);
  assert.ok(rel(Z99, "kA", 31) < -0.0044 && rel(Z90, "kB", 31) < -0.0052);
  assert.ok(rel(Z99, "kA", 300) > -0.001 && rel(Z90, "kB", 300) > -0.001);
});

test("both screens use the same k (qualification == aerospace, bit for bit)", () => {
  for (let N = -5; N <= 600; N++) {
    const q = computeQualificationMmpdsStats({
      meanYieldMpa: 930,
      meanTensileMpa: 1010,
      fractureToughnessMpaM: 68,
      sampleSizeN: N,
      customScatterCv: 2.8,
    });
    const a = computeAerospaceScreeningStats({ meanYieldMpa: 930, meanTensileMpa: 1010, sampleSizeN: N, scatterCvPct: 2.8 });
    assert.ok(Object.is(q.kA, a.kA) && Object.is(q.kB, a.kB), `N=${N}`);
  }
});

// ---------------------------------------------------------------------------------------------------------------
// HISTORICAL (bug fixed 2026-10): StandardQualificationEngine used k = z_p + sqrt(z_p^2 - a b) / a (the division
// bound only to the sqrt). Re-implemented here verbatim so the delta stays visible to reviewers.
// ---------------------------------------------------------------------------------------------------------------
function oldMisgroupedK(z: number, N: number): number {
  return Number(
    (z + Math.sqrt(z * z - (1 - (ZG * ZG) / (2 * (N - 1))) * (z * z - (ZG * ZG) / N)) / (1 - (ZG * ZG) / (2 * (N - 1)))).toFixed(3)
  );
}

test("HISTORICAL old qualification k: pinned values, optimistic against the exact factor at every N", () => {
  const pinned = Object.fromEntries([10, 30, 60, 100].map((N) => [N, [oldMisgroupedK(Z99, N), oldMisgroupedK(Z90, N)]]));
  assert.deepEqual(pinned, { 10: [3.528, 2.094], 30: [2.937, 1.705], 60: [2.746, 1.574], 100: [2.648, 1.506] });
  for (let N = 10; N <= 300; N++) {
    const e = exact.get(N)!;
    assert.ok(oldMisgroupedK(Z99, N) < e.kA && oldMisgroupedK(Z90, N) < e.kB, `N=${N}`);
  }
  // at N = 10 the old k was 11.4 % (A) / 11.1 % (B) below exact
  assert.ok((exact.get(10)!.kA - 3.528) / exact.get(10)!.kA > 0.11);
  assert.ok((exact.get(10)!.kB - 2.094) / exact.get(10)!.kB > 0.11);
});

test("HISTORICAL Natrella k used by both screens between the grouping fix and the exact table (aerospace since inception)", () => {
  const pinned = Object.fromEntries(
    [10, 12, 20, 30, 35, 45, 50, 60, 100].map((N) => [N, [natrellaOneSidedToleranceFactor(Z99, N), natrellaOneSidedToleranceFactor(Z90, N)]])
  );
  assert.deepEqual(pinned, {
    10: [3.94, 2.321],
    12: [3.712, 2.182],
    20: [3.274, 1.91],
    30: [3.05, 1.767],
    35: [2.983, 1.724],
    45: [2.889, 1.662],
    50: [2.855, 1.64],
    60: [2.801, 1.604],
    100: [2.68, 1.524],
  });
});

test("report method label follows the method actually used (CoC PDF text)", () => {
  assert.equal(toleranceFactorMethodLabel(0), "exact noncentral-t"); // screens clamp N to 10
  assert.equal(toleranceFactorMethodLabel(12), "exact noncentral-t");
  assert.equal(toleranceFactorMethodLabel(300), "exact noncentral-t");
  assert.equal(toleranceFactorMethodLabel(300.5), "exact noncentral-t"); // floor(N) row
  assert.equal(toleranceFactorMethodLabel(301), "Lieberman-Resnikoff");
  assert.equal(toleranceFactorMethodLabel(Number.NaN), "Lieberman-Resnikoff");
});
