import { ResponsiveContainer } from '../VisibleResponsiveContainer';
import React from "react";
import { SimulationJob, SimulationResult } from "../../services/lpbfSimulationService";
import { LineChart, Line, XAxis, YAxis, Tooltip, ReferenceDot, CartesianGrid, ReferenceArea, ReferenceLine } from "recharts";

export const number = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? (value!==0 && (Math.abs(value)<.001 || Math.abs(value)>=1e7) ? value.toExponential(2) : value.toLocaleString("en-US", { maximumSignificantDigits: 5 })) : "—";
export const surface = "rounded-2xl border border-slate-700/60 bg-slate-900/40 p-5 sm:p-6";
type MatchState = "match" | "mismatch" | "missing";
const measurementMatchState = (value: string | null | undefined): MatchState => {
  if (!value) return "missing";
  return /yes|true|exact|matched/i.test(value) ? "match" : /no|false|different/i.test(value) ? "mismatch" : "missing";
};
const pluralize = (count: number, singular: string, plural: string) => `${count} ${count === 1 ? singular : plural}`;
const measurementMatchLabel = (match: MatchState) => match === "match" ? "process-vector exact" : match === "mismatch" ? "process mismatch" : "provenance missing";

const measurementSummary = (result: SimulationResult): { status: MatchState; details: string[] } => {
  const evidence = result.measurementEvidence ?? [];
  const comparison = result.measurementComparison;
  if (!evidence.length && !comparison) return { status: "missing", details: ["No paired measurement evidence supplied."] };
  if (!comparison) return { status: "missing", details: ["Measurements were supplied; calibration summary is not available in this result."] };
  const matched = evidence.filter(item => measurementMatchState(item.sameProcessVector) === "match");
  const mismatched = evidence.filter(item => measurementMatchState(item.sameProcessVector) === "mismatch");
  const unknown = evidence.filter(item => measurementMatchState(item.sameProcessVector) === "missing");
  const independent = evidence.filter(item => item.independentHoldout).length;
  const details = [
    `Comparison metrics are available for ${pluralize(Object.keys(comparison).length, "dimension panel", "dimension panels")}.`,
    `${pluralize(matched.length, "replicate", "replicates")} report ${measurementMatchLabel("match")}.`,
    mismatched.length ? `${pluralize(mismatched.length, "replicate", "replicates")} report ${measurementMatchLabel("mismatch")}.` : "No process mismatch in returned evidence.",
    unknown.length ? `${pluralize(unknown.length, "replicate", "replicates")} have ${measurementMatchLabel("missing")}.` : "Process-vector provenance for returned evidence is complete.",
    independent ? `${pluralize(independent, "replicate", "replicates")} are user-declared independent holdout.` : "No user-declared independent holdout replicate was provided.",
  ];
  return {
    status: mismatched.length > 0 ? "mismatch" : unknown.length > 0 ? "missing" : matched.length > 0 ? "match" : "missing",
    details,
  };
};
export function Badge({ children, tone = "warning" }: { children: React.ReactNode; tone?: "warning" | "active" | "error" | "neutral" }) {
  return <span className={`inline-flex items-center rounded-md border px-2.5 py-1 text-xs leading-5 ${tone === "active" ? "border-sky-400/25 bg-sky-400/10 text-sky-200" : tone === "error" ? "border-red-400/30 bg-red-400/10 text-red-200" : tone === "neutral" ? "border-slate-600/60 bg-slate-800/60 text-slate-300" : "border-amber-400/25 bg-amber-400/10 text-amber-200"}`}>{children}</span>;
}
export function ResultHeader({ job, material, availability, stale, elapsed, cancel, cancelling }: { job?: SimulationJob; material: string; availability: string; stale: boolean; elapsed: number; cancel: () => void; cancelling: boolean }) {
  const r = job?.status === "completed" ? job.result : undefined;
  const active = job?.status === "running" || job?.status === "queued";
  const failed = job?.status === "failed" || job?.status === "timed_out";
  const status = job?.status === "completed" && job.cacheHit ? "Cached · completed" : job?.status.replaceAll("_", " ") || "Ready to configure";
  const comparison = r ? measurementSummary(r) : undefined;
  const partial = job && ["failed", "cancelled", "timed_out"].includes(job.status) ? job.partialArtifacts : undefined;
  return <section aria-label="Engineering result header" className="overflow-hidden rounded-2xl border border-slate-600/50 bg-gradient-to-br from-slate-800/70 via-slate-900/80 to-[#080f1c]">
    <div className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-700/50 px-6 py-5"><div><p className="text-[11px] uppercase tracking-[.22em] text-slate-400">{r ? "Simulation result" : "Engineering workspace"} / {r?.material.name || material}</p><h4 className="mt-2 text-xl font-medium tracking-tight">{r?.label || "Melt pool response"}</h4></div><div className="flex flex-wrap gap-2"><Badge tone={active ? "active" : failed ? "error" : "neutral"}>{status}</Badge><Badge>Experimental validation pending</Badge><Badge tone={comparison?.status === "mismatch" ? "warning" : comparison?.status === "match" ? "active" : "neutral"}>{comparison ? `Calibration ${comparison.status === "match" ? "process-matched" : comparison.status === "mismatch" ? "process mismatch" : "incomplete"}` : "Calibration unavailable"}</Badge></div></div>
    <dl className="grid grid-cols-2 gap-x-5 gap-y-7 px-6 py-8 xl:grid-cols-4">{[["Length", r?.metrics.length_um, "µm"], ["Width", r?.metrics.width_um, "µm"], ["Depth", r?.metrics.depth_um, "µm"], ["Peak temperature", r?.metrics.peakTemperature_K, "K"]].map(([label, value, unit]) => <div key={String(label)}><dt className="text-xs tracking-wide text-slate-400">{String(label)}</dt><dd className="mt-3 text-3xl font-medium tracking-tight tabular-nums sm:text-4xl">{number(value)} <span className="text-sm font-normal text-slate-400">{String(unit)}</span></dd><p className="mt-2 text-[11px] leading-5 text-slate-400">{r?(r.effectiveMode==="screening"?(label==="Peak temperature"?"Not resolved in this screening run":"Goldak · analytical liquidus extent"):label==="Peak temperature"?"Resolved thermal · all timesteps":(r.numericalDiagnostics?.meltPoolExtraction === "accepted-step-molten-volume-v1" ? "Resolved liquidus cells · maximum over accepted timesteps" : "Resolved liquidus cells · maximum sampled volume")):"Source pending"}</p></div>)}</dl>
    <div className="grid gap-5 border-y border-slate-700/50 px-6 py-5 lg:grid-cols-[1fr_1.3fr]"><div className="space-y-3"><div className="flex flex-wrap gap-2"><Badge>Regime · {r?.regime || "Not evaluated"}</Badge><Badge>Main risk · {r?.mainRisk || "Not evaluated"}</Badge></div><p className="text-xs leading-6 text-slate-400">{r?.riskScope || "Submit a run to obtain geometry and a scoped defect screening assessment."}</p></div><div><p className="text-[11px] uppercase tracking-widest text-slate-400">Recommended parameter change</p><p className="mt-2 text-sm leading-6">{r?.recommendation || "Awaiting simulation. No process recommendation has been established."}</p></div></div>
    <dl className="grid grid-cols-2 gap-5 px-6 py-5 lg:grid-cols-4">{[["Confidence", r ? `${r.confidence} · model evidence limited` : "Not assessed"], ["Solver used", r?.solver.id || (active ? `${job?.requestSummary?.backend || "Worker"} · allocation pending confirmation` : "Not run")], ["Material data quality", r?.material.quality || "Inspect material evidence"], ["OpenFOAM availability", availability], ["Calibration", comparison?.status === "match" ? "Process-matched replicates available" : comparison?.status === "mismatch" ? "Replicates include process mismatch" : "Incomplete calibration status"], ["Cache status", !job ? "Not checked" : job.cacheHit ? "Hit · saved result reused" : job.deduplicated ? "Joined existing job" : "New computation"], ["Energy balance", r?.energyBalance ? `${number(r.energyBalance.relativeError * 100)}% closure error` : "Not reported"], ["Mass balance", r?.massBalance ? `${number(r.massBalance.relativeError * 100)}% closure error` : "Not reported"], ["Job time", active ? `${Math.floor(elapsed)} s since submission / recovery · ETA unavailable` : r?.provenance?.runtime_s!==undefined ? `${number(r.provenance.runtime_s)} s solver execution` : "See worker log for execution timing"]].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1.5 break-words text-sm">{value}</dd></div>)}</dl>
    {r?.discretization&&[r.metrics.width_um,r.metrics.depth_um].some(v=>v>0&&v/(r.discretization!.mesh_m*1e6)<=2)&&<p role="status" className="px-6 pb-4 text-xs text-amber-200">Under-resolved geometry: width or depth spans at most two cells. Refine the mesh and check sensitivity before interpreting dimension ratios or defect screening.</p>}
    {r?.provenance?.createdAt&&<p className="px-6 pb-4 text-xs text-slate-400">Result timestamp · {r.provenance.createdAt}</p>}
    {job && <div className="border-t border-slate-700/50 px-6 py-4" role="status" aria-live="polite"><div className="mb-2 flex items-center justify-between gap-3 text-xs"><span className="capitalize">{status} · {number(job.progress * 100)}% reported</span>{active && <button disabled={cancelling} onClick={cancel} className="rounded-lg border border-slate-500 px-4 py-2 text-sm hover:bg-slate-700 disabled:opacity-50">{cancelling ? "Cancelling…" : "Cancel"}</button>}</div><div role="progressbar" aria-label="Job progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={job.progress*100} className="h-1.5 w-full overflow-hidden rounded-full bg-slate-800"><div className={`h-full ${failed?"bg-red-400":active?"bg-sky-400":"bg-slate-400"}`} style={{width:`${job.progress*100}%`}}/></div>{!active && !r && <p className="mt-3 text-sm text-amber-200">No completed result. {job.status === "timed_out" ? "Worker timeout reached; review numerical cost before retrying." : "Review the worker log before submitting another run."}</p>}{partial?.status === "retained-unverified" && <p className="mt-3 text-sm text-amber-200">{partial.fileCount} partial files retained locally ({partial.totalBytes} bytes). Integrity not verified; unavailable as a result/download and excluded from completed-run archives.</p>}{partial?.status === "inventory-unavailable" && <p className="mt-3 text-sm text-amber-200">Partial output inventory unavailable; no integrity claim.</p>}</div>}
    {stale && r && <p role="status" className="border-t border-amber-400/20 bg-amber-400/5 px-6 py-3 text-sm text-amber-200">Saved result · inputs have changed. Run again to evaluate the current process vector.</p>}
  </section>;
}

export function ThermalHistory({ result, currentTime }: { result: SimulationResult; currentTime?: number }) {
  const history = result.thermalHistory;
  if (!history?.length) return <section className={surface}><h4 className="font-medium">Thermal history</h4><p className="mt-3 text-sm text-slate-400">Not resolved in this screening run. Select Standard Simulation for transient thermal history.</p></section>;
  const data = history.map(h => ({ time: h.time_s * 1000, temperature: h.peak_K }));
  const liquidus=result.material.liquidus_K;
  const crossings=typeof liquidus==="number"&&Number.isFinite(liquidus)?data.slice(1).flatMap((h,i)=>{const prev=data[i];return (prev.temperature-liquidus)*(h.temperature-liquidus)<0?[{time:prev.time+(h.time-prev.time)*(liquidus-prev.temperature)/(h.temperature-prev.temperature),temperature:liquidus}]:[];}):[];
  const peak = data.reduce((a, b) => b.temperature > a.temperature ? b : a);
  return <section className={surface} aria-label="Thermal history"><h4 className="font-medium">Thermal history</h4><p className="mt-1 text-xs text-slate-400">Domain peak temperature · K / elapsed time · ms</p><div className="mt-6 h-64 min-w-0"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 25, right: 24, bottom: 15, left: 0 }} accessibilityLayer><CartesianGrid stroke="#253245" vertical={false}/><XAxis dataKey="time" type="number" domain={[0, "dataMax"]} tickFormatter={v => number(v)} unit=" ms" stroke="#94a3b8" tick={{ fontSize: 11 }}/><YAxis stroke="#94a3b8" tick={{ fontSize: 11 }} width={60}/><Tooltip formatter={v => [`${number(v)} K`, "Domain peak"]} labelFormatter={v => `${number(v)} ms`} contentStyle={{ background: "#0f172a", border: "1px solid #475569", borderRadius: 10 }}/>{result.scanPath?.map((s, i) => <React.Fragment key={i}><ReferenceArea x1={s.start_s * 1000} x2={s.end_s * 1000} className="fill-amber-400/10 stroke-none"/></React.Fragment>)}{typeof liquidus==="number"&&Number.isFinite(liquidus)&&<ReferenceLine y={liquidus} stroke="#f59e0b" strokeDasharray="4 5"/>}{crossings.map((c,i)=><React.Fragment key={`cross-${i}`}><ReferenceDot x={c.time} y={c.temperature} r={3} fill="#f59e0b" stroke="#fcd34d"/></React.Fragment>)}{currentTime!==undefined&&<ReferenceLine x={currentTime*1000} stroke="#22d3ee" strokeDasharray="3 3"/>}<Line type="linear" dataKey="temperature" stroke="#60a5fa" strokeWidth={2} dot={false} isAnimationActive={false}/><ReferenceDot x={peak.time} y={peak.temperature} r={4} fill="#f97316" stroke="#fdba74" label={{ value: `Peak ${number(peak.temperature)} K`, position: "top", fill: "#fdba74", fontSize: 11 }}/></LineChart></ResponsiveContainer></div><p className="text-xs leading-6 text-slate-400">Cyan vertical line: displayed field snapshot. Amber bands: laser on. Gaps between tracks: dwell. After the last track: cooling. Dashed amber line / dots: liquidus and interpolated domain-maximum crossings when material data is available. This is not a material-point trace; local liquidus crossing events are not recoverable from this curve.</p></section>;
}

export function ConvergencePanel({ study }: { study: SimulationResult["convergenceStudy"] }) {
  // The optional audit is deliberately guarded: older workers may omit its structure.
  const s = study as { kind?: string; status?: string; protocol?: string; requestedBackend?: string; executionBackend?: string; cellsPerLayer?: number[]; spacings?: (number | null)[]; results?: (Record<string, number> | null)[]; checks?: Record<string, { status: string; observedOrder?: number; fineGCI_pct?: number; reason?: string }> } | undefined;
  const alignedCpuStudy = s?.protocol === "layer-aligned-three-grid-cpu-reference-v1";
  const requestedBackend = s?.requestedBackend === "auto" ? "automatic" : s?.requestedBackend || "reference";
  return <section className={surface}><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="font-medium">Numerical convergence</h4><Badge tone="neutral">{s?.kind || "Not run"} · {s?.status || "numerical evidence only"}</Badge></div>{alignedCpuStudy && <p className="mt-3 text-xs leading-5 text-slate-300">Layer-aligned CPU reference study · requested backend: {requestedBackend} · execution backend: {s.executionBackend || "reference"} · cells per layer: {s.cellsPerLayer?.join(" / ") || "not recorded"}.</p>}{Array.isArray(s?.results) && <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[460px] text-left text-sm"><caption className="sr-only">Coarse, medium and fine discretization results</caption><thead className="text-xs text-slate-400"><tr>{["Resolution", s.kind === "mesh" ? "Spacing · m" : "Mean timestep · s", "Width · µm", "Depth · µm"].map(h => <th key={h} className="pb-3 font-normal">{h}</th>)}</tr></thead><tbody>{s.results.map((r, i) => <tr key={i} className="border-t border-slate-700/50"><th className="py-3 font-normal">{["Coarse", "Medium", "Fine"][i]}</th><td>{number(s.spacings?.[i])}</td><td>{r ? number(r.width_um) : "Unavailable"}</td><td>{r ? number(r.depth_um) : "Unavailable"}</td></tr>)}</tbody></table></div>}{s?.checks && Object.entries(s.checks).map(([key, c]) => <p key={key} className="mt-3 text-sm text-slate-300">{key} · {c.status} · observed order {number(c.observedOrder)} · fine GCI {number(c.fineGCI_pct)}% {c.reason}</p>)}<p className="mt-4 text-xs text-slate-400">{s ? "A converging sequence does not establish a tolerance-qualified converged result or experimental validation." : "Select a mesh or timestep study in Numerical controls to compare three resolutions."}</p></section>;
}

export function MeasurementPanel({ result }: { result: SimulationResult }) {
  const measurements = result.settings.measurements || [];
  const summary = measurementSummary(result);
  return <section className={surface} aria-label="Experimental comparison"><h4 className="font-medium">Experimental comparison</h4><p className="my-3 text-sm text-amber-200">Calibration improves comparison reporting. It does not establish independent validation and is not automatically applied to the solver.</p><div className="mb-4 rounded-lg border border-slate-700/50 bg-slate-900/30 px-3 py-2 text-xs text-slate-300"><p className="font-medium">Calibration readiness</p><p className="mt-2 text-slate-400">Status: {summary.status}</p><ul className="mt-2 list-disc space-y-1 pl-5 text-slate-400">{summary.details.map(d => <li key={d}>{d}</li>)}</ul></div>{!result.measurementComparison && <p className="text-sm text-slate-400">No paired measurements supplied. Experimental validation pending.</p>}{result.measurementComparison && Object.entries(result.measurementComparison).map(([key, c]) => <div key={key} className="mt-5 border-t border-slate-700/50 pt-4"><h5 className="text-sm font-medium">{key.replace("_um", "")} · {c.count} replicates</h5><p className="mt-2 text-sm">RMSE {number(c.rmse_um)} µm · bias {number(c.bias_um)} µm · calibration factor {number(c.calibrationFactor)}</p><p className="mt-2 text-xs text-slate-400">Signed error: {c.errors_pct.map(number).join(", ")}% · {c.note}</p></div>)}{measurements.length > 0 && <div className="mt-5 h-60"><ResponsiveContainer width="100%" height="100%"><LineChart data={measurements.map((m, i) => ({ replicate: i + 1, width: m.width_um, depth: m.depth_um, predictedWidth: result.metrics.width_um, predictedDepth: result.metrics.depth_um }))} accessibilityLayer><CartesianGrid stroke="#253245"/><XAxis dataKey="replicate" stroke="#94a3b8"/><YAxis unit=" µm" width={70} stroke="#94a3b8"/><Tooltip contentStyle={{ background: "#0f172a", borderColor: "#475569" }}/><Line name="Measured width" dataKey="width" stroke="#94a3b8" isAnimationActive={false}/><Line name="Predicted width" dataKey="predictedWidth" stroke="#94a3b8" strokeDasharray="5 4" isAnimationActive={false}/><Line name="Measured depth" dataKey="depth" stroke="#e2e8f0" isAnimationActive={false}/><Line name="Predicted depth" dataKey="predictedDepth" stroke="#e2e8f0" strokeDasharray="5 4" isAnimationActive={false}/></LineChart></ResponsiveContainer><p className="text-xs text-slate-400">Replicate index · solid lines: supplied measurements; dashed lines: solver predictions. Grey: width; white: depth.</p></div>}{result.measurementEvidence?.map((e, i) => <p key={i} className="mt-5 break-words text-xs leading-6 text-slate-400">Source / specimen / DOI: {e.source} · process match: {e.sameProcessVector} · independent holdout: {e.independentHoldout == null ? "unknown" : e.independentHoldout ? "user-declared; not independently verified" : "calibration data"} · measurement uncertainty: {e.uncertainty_um ? JSON.stringify(e.uncertainty_um) : "not supplied"}</p>)}</section>;
}
