// Derives scripts/demo/demo-requests.json from the app's own request builders (run: npx tsx scripts/demo/derive-demo-requests.ts).
// The guided NIST IN718 case is read from the committed literature case and the preset store, never typed here.
// The request bodies mirror what the UI sends: LpbfProcessWindowMap, LpbfEngineeringSimulation (Quick Screening),
// MeltPool3DCrossSectionLab + CalibratedMeltpoolPanel (goldak, IR_1064nm, sulfur 15 ppm defaults).
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { demoCase, demoProcessPatch } from '../../src/utils/guidedDemo.ts';
import { useMaterialSpecimenStore } from '../../src/store/useMaterialSpecimenStore.ts';
import { LPBF_ENGINEERING_DEFAULTS } from '../../src/store/useLpbfEngineeringStore.ts';
import { sharedSimulationInput } from '../../src/utils/lpbfQualificationReport.ts';
import { mapSpecimenToBuildJobMaterials } from '../../src/utils/lpbfIndustrialDecision.ts';
import { resolveOptimizerAlloy } from '../../src/utils/lpbfOptimizerAlloy.ts';
import { PROCESS_WINDOW_BEAM_TOLERANCE_PCT } from '../../src/data/lpbfProcessWindow.ts';
import { DEFAULT_EXCLUDED_FIELDS } from '../../src/demo/demoKey.ts';

const c = demoCase();
useMaterialSpecimenStore.getState().loadPreset('inconel-718');
useMaterialSpecimenStore.getState().updateLpbfProcess(demoProcessPatch(c));
const specimen = useMaterialSpecimenStore.getState().activeSpecimen;
const lpbf = specimen.lpbf;
const alloy = resolveOptimizerAlloy(specimen.name);
if (!alloy.ok || !alloy.alloyKey) throw new Error('The guided specimen has no supported optimizer alloy.');
const thermalMaterial = mapSpecimenToBuildJobMaterials(specimen.name, specimen.baseMetal)?.pythonThermal;
if (!thermalMaterial) throw new Error('The guided specimen has no analytical melt pool material.');

const analytical = {
  material: thermalMaterial, laserPower_W: lpbf.laserPower_W, scanSpeed_mm_s: lpbf.scanSpeed_mms, beamDiameter_um: lpbf.beamDiameter_um,
  preheatTemp_C: lpbf.preheatTemp_C, layerThickness_um: lpbf.layer_um, hatchSpacing_um: lpbf.hatch_um,
  laserWavelength: 'IR_1064nm', heatSource: 'goldak', sulfur_ppm: 15,
};
const strategy = lpbf.scanStrategy === 'meander-67' ? 'meander' : lpbf.scanStrategy;
const screeningJob = { ...sharedSimulationInput(specimen), ...LPBF_ENGINEERING_DEFAULTS, mode: 'screening', strategy };

const requests = [
  { label: 'Process window, IN718 guided case (engine default axes)', group: 'process-window', source: 'engine', method: 'POST', path: '/api/python/lpbf-process-window',
    body: { alloyId: alloy.alloyKey, beamDiameter_um: lpbf.beamDiameter_um, layer_um: lpbf.layer_um, hatch_um: lpbf.hatch_um, preheatTemp_C: lpbf.preheatTemp_C, overlayBeamTolerance_pct: PROCESS_WINDOW_BEAM_TOLERANCE_PCT } },
  { label: 'Thermal solver (analytical melt pool), guided case', group: 'guided-chain', source: 'engine', method: 'POST', path: '/api/python/lpbf-thermal-solver', body: analytical },
  { label: 'Calibrated melt pool (opt-in), guided case', group: 'guided-chain', source: 'engine', method: 'POST', path: '/api/python/lpbf-calibrated-meltpool', body: { ...analytical, calibrationMode: true } },
  { label: 'Quick Screening job, guided case (final completed job)', group: 'guided-chain', source: 'engine-job', method: 'POST', path: '/api/lpbf/jobs', body: screeningJob },
  { label: 'Engine status fixture', group: 'engine-status', source: 'fixture', method: 'GET', path: '/api/python/status',
    fixture: { success: true, status: 'static snapshot', platform: 'static-demo', warm: false, channel: 'static-demo', subsystemStatus: 'static snapshot' } },
  { label: 'Health fixture', group: 'engine-status', source: 'fixture', method: 'GET', path: '/api/health',
    fixture: { status: 'ok', service: 'MetalliX-Static-Demo', hasApiKey: false, airgapped: false } },
  { label: 'Runtime config fixture', group: 'engine-status', source: 'fixture', method: 'GET', path: '/api/runtime-config',
    fixture: { airgapped: false, blockedServices: [], allowedLocal: [], staticDemo: true } },
];

const doc = {
  note: 'Generated by scripts/demo/derive-demo-requests.ts from the app request builders. source: engine = call the local engine, engine-job = POST then poll until a final state and also record GET /api/lpbf/jobs/<id>, fixture = fixed body, no engine call.',
  excludedFields: [...DEFAULT_EXCLUDED_FIELDS],
  requests,
};
const out = path.join(path.dirname(fileURLToPath(import.meta.url)), 'demo-requests.json');
writeFileSync(out, JSON.stringify(doc, null, 2) + '\n');
console.log('wrote', out);
