// Pourbaix E-pH (25 °C, single-element M-H2O) types. The species table is generated by
// python/pourbaix_species_25c.py (src/generated/pourbaixSpecies25C.json); this file only types it.

/** Engine category ids (python/pourbaix_species_25c.py CATEGORY_BY_ROLE). */
export type StabilityCategory =
  | "Immunity"
  | "Corrosion (acid)"
  | "Corrosion (alkaline)"
  | "Passivation (thermodynamic, film-forming)"
  | "Transpassive";

export type PourbaixRole = "metal" | "cation" | "anion_low" | "oxide" | "anion_high";

export type ReferenceElectrode = "SHE" | "SCE" | "Ag/AgCl (3M KCl)" | "Ag/AgCl (Sat KCl)" | "CSE" | "MMS";

/** One row of the generated species table (formation Gibbs energy at 25 °C, kJ/mol). */
export interface PourbaixSpeciesRow {
  id: string;
  formula: string;
  x: number; // metal atoms
  o: number; // O atoms
  h: number; // H atoms
  z: number; // charge
  phase: "s" | "aq";
  dfG_kJ_mol: number;
  role: PourbaixRole;
  category: StabilityCategory;
  source: string;
  verification: string;
  evidence: string;
}

/** A withheld alternative dataset (python/pourbaix_species_25c.py CANDIDATE_SETS): ids of withheldSpecies rows. */
export interface PourbaixCandidateSet {
  id: string;
  label: string;
  speciesIds: string[];
}

export interface PourbaixAvailableElement {
  name: string;
  available: true;
  sourceSet: string;
  sourceSetNote: string;
  waterDfG_kJ_mol: number;
  /** null when the table has no verified cation (Cr, Mo, Ti): no unit-activity metal/cation E0. */
  referenceCation: string | null;
  /** log10 dissolved activity accepted for this element (Cr and Mo are narrower than the global range). */
  activityLog10Range: [number, number];
  species: PourbaixSpeciesRow[];
  /** Rows not used by the engine (rejected, contradictory or excluded), with their values. */
  withheldSpecies?: PourbaixSpeciesRow[];
  candidateSets: PourbaixCandidateSet[];
  unsourcedSpecies: { formula: string; reason: string }[];
}

export interface PourbaixUnavailableElement {
  name: string;
  available: false;
  reason: string;
}

export interface PourbaixSpeciesData {
  schema: string;
  temperature_C: number;
  temperature_K: number;
  constants: { gasConstantR_J_molK: number; faraday_C_mol: number; ln10: number };
  activity: { log10Range: [number, number]; log10Default: number; coefficients: string };
  box: { pH_min: number; pH_max: number; E_min_V_SHE: number; E_max_V_SHE: number };
  water: { dfG_NBS_kJ_mol: number; e0_O2_H2O_V: number };
  roles: Record<PourbaixRole, StabilityCategory>;
  elements: Record<string, PourbaixAvailableElement | PourbaixUnavailableElement>;
}

/** g_i(pH, E) = c0 + cpH*pH + cE*E (J per metal atom) for one species at a fixed dissolved activity. */
export interface SpeciesCoefficients {
  id: string;
  formula: string;
  phase: "s" | "aq";
  role: PourbaixRole;
  category: StabilityCategory;
  c0: number;
  cpH: number;
  cE: number;
}

export type PourbaixPolygon = [number, number][]; // (pH, E_V_SHE) vertices

export interface PourbaixDomain {
  speciesId: string;
  formula: string;
  category: StabilityCategory;
  polygon: PourbaixPolygon;
}

export interface PourbaixPointState {
  ph: number;
  potential_V: number;
  speciesId: string;
  formula: string;
  category: StabilityCategory;
  isInsideWaterStability: boolean;
}

/** Domain that a withheld candidate species would take if its candidate set were added: the map is not valid there. */
export interface PourbaixWithheldRegion {
  candidateSet: string;
  speciesId: string;
  formula: string;
  polygon: PourbaixPolygon;
}

export interface AlloyPreset {
  id: string;
  name: string;
  category: "Nickel Superalloy" | "Titanium Alloy" | "High-Entropy Alloy (HEA)" | "Stainless Steel" | "Aluminum Alloy" | "Copper Alloy" | "Pure Metal";
  description: string;
  composition: { [element: string]: number }; // wt%
  recommendedApplication: string;
}

export interface WaterStabilityLines {
  herLine: { e_at_ph0: number; slope: number }; // Line a: 2H+ + 2e- <=> H2(g)
  oerLine: { e_at_ph0: number; slope: number }; // Line b: O2(g) + 4H+ + 4e- <=> 2H2O
  nernstSlope: number;
}

export type PourbaixBoundaryEquation =
  | { type: "sloped"; E_V_SHE_at_pH0: number; slope_V_per_pH: number }
  | { type: "vertical"; pH: number };

export interface AnalyticalBoundaryLine {
  id: string;
  name: string;
  equation: string;
  boundaryType: string;
  speciesA: string;
  speciesB: string;
  speciesAId?: string;
  speciesBId?: string;
  line?: PourbaixBoundaryEquation | null;
  points: { pH: number; E_V_SHE: number }[]; // the two exact ends of the segment
}

export interface ExperimentalEpHEntry {
  id: string;
  name: string;
  pH: number;
  potential_V: number; // Input potential in refElectrode scale
  refElectrode: ReferenceElectrode;
  potential_V_SHE?: number; // Standardized potential vs SHE
  currentDensity_uA_cm2?: number;
  timeHours?: number;
  stageName?: string;
  notes?: string;

  // Diagnostics returned from Python equilibrium solver
  regime?: string;
  category?: StabilityCategory;
  dominantSpecies?: string;
  dominantSpeciesId?: string;
  mechanismId?: string;
  mechanismTitle?: string;
  mechanismDetails?: string;
  /** Display label derived by the engine from the thermodynamic category; no rate or protectiveness claim. */
  riskLevel?: "Immune" | "Stable Passivity" | "Caution" | "Pitting Hazard" | "Severe Corrosion" | "High Risk";
  color?: string;
  depolarizer?: string;
  deltaE_Immunity_V?: number | null;
  deltaE_Pitting_V?: number | null;
  isInsideWaterStability?: boolean;
  waterStabilityLabel?: string;
  engineeringMitigations?: string[];
}

export interface ExperimentalEpHTrajectoryPreset {
  id: string;
  name: string;
  element: string;
  description: string;
  environmentSummary: string;
  points: ExperimentalEpHEntry[];
}

export interface PythonPourbaixResult {
  success: boolean;
  engine: string;
  computeTimeMs: number;
  element: string;
  systemName: string;
  parameters: {
    temperature_C: number;
    requestedTemperature_C?: number;
    nernstSlope_V_pH: number;
    ionActivity_log10: number;
    chlorideConcentration_ppm: number;
    chloride_Molar: number;
    pittingPotential_V_SHE: number | null;
    pittingRisk: string;
    standardE0_V?: number | null;
  };
  temperatureStatus?: { status: string; temperature_C: number; supported_C: number[]; toleranceC: number; note: string };
  model?: Record<string, unknown>;
  speciesTable?: { sourceSet: string; sourceSetNote: string; waterDfG_kJ_mol: number; schema: string; species: PourbaixSpeciesRow[]; withheldSpecies: { id: string; verification: string; reason: string }[] };
  dataValidity?: {
    status: string;
    activityRange_log10: [number, number];
    rule: string;
    candidateSets: PourbaixCandidateSet[];
    regions: { candidateSet: string; speciesId: string; formula: string; category: StabilityCategory; polygon: { pH: number; E_V_SHE: number }[] }[];
    pHWindowsFreeOfRegionsInsideWater: [number, number][];
    unsourcedSpecies: { formula: string; reason: string }[];
  };
  waterStabilityLines: {
    nernstSlope: number;
    e0_OER: number;
    line_a_hydrogen_HER: { pH: number; E_V_SHE: number }[];
    line_b_oxygen_OER: { pH: number; E_V_SHE: number }[];
    equation_HER: string;
    equation_OER: string;
  };
  chloridePittingBoundary: {
    pittingActive: boolean;
    status?: string;
    chloride_ppm?: number;
    chloride_Molar?: number;
    nominal_Epit_V_SHE?: number | null;
    note?: string;
  };
  analyticalBoundaries: AnalyticalBoundaryLine[];
  domains?: { speciesId: string; category: StabilityCategory; polygon: { pH: number; E_V_SHE: number }[] }[];
  speciesInventory: {
    immunity: string[];
    corrosion_acid: string[];
    passivation: string[];
    corrosion_alkaline: string[];
    transpassive?: string[];
  };
  stabilityFieldGrid: {
    pH: number;
    E_V_SHE: number;
    regime: string;
    category?: StabilityCategory;
    dominantSpecies: string;
    dominantSpeciesId?: string;
    mechanismTitle: string;
    color: string;
    isInsideWaterStability?: boolean;
  }[];
  experimentalOverlay?: {
    totalPointsCount: number;
    riskBreakdown: {
      Immune: number;
      "Stable Passivity": number;
      Caution: number;
      "Pitting Hazard": number;
      "Severe Corrosion": number;
      "High Risk": number;
    };
    overallTrajectoryDiagnosis: string;
    points: ExperimentalEpHEntry[];
  };
}
