// Pourbaix E-pH equilibrium, 25 °C, single element M-H2O. TypeScript port of the Python engine
// (python/pourbaix_solver.py): minimum Gibbs energy per metal atom over the sourced species table
// (src/generated/pourbaixSpecies25C.json, emitted by python/pourbaix_species_25c.py), fixed dissolved
// activity, gamma = 1. The stable species at (pH, E) is argmin g_i with
//   g_i = [dfG_i - o_i*dfG(H2O) + RT ln a_i]/x_i - m_i ln10 RT pH - n_i F E,
//   m_i = (2 o_i - h_i)/x_i,  n_i = (z_i + 2 o_i - h_i)/x_i,  a_i = 1 for solids.
// Every g_i is affine in (pH, E), so each domain is a convex polygon (Sutherland-Hodgman against the other
// species). No E0, slope, reaction or temperature model is entered by hand. tests/pourbaix-equilibrium.test.ts
// checks this port against a 200x200 classification generated by the Python engine.

import speciesJson from "../generated/pourbaixSpecies25C.json";
import type {
  AlloyPreset,
  PourbaixDomain,
  PourbaixPointState,
  PourbaixPolygon,
  PourbaixSpeciesData,
  PourbaixSpeciesRow,
  PourbaixBoundaryEquation,
  SpeciesCoefficients,
  StabilityCategory,
  WaterStabilityLines,
} from "../types/pourbaix";

export const POURBAIX_DATA = speciesJson as unknown as PourbaixSpeciesData;
const { constants: K, box: BOX } = POURBAIX_DATA;
const RT = K.gasConstantR_J_molK * POURBAIX_DATA.temperature_K; // J/mol
/** ln10 RT / F in V per pH unit (0.05916 V at 25 °C). */
export const NERNST_SLOPE_25C = (K.ln10 * RT) / K.faraday_C_mol;

// ---------------------------------------------------------------------------
// Element availability (the engine's POURBAIX_DATA_UNAVAILABLE reasons are the JSON `reason` strings)
// ---------------------------------------------------------------------------

export function availablePourbaixElements(): string[] {
  return Object.keys(POURBAIX_DATA.elements).filter((e) => POURBAIX_DATA.elements[e].available);
}

/** null when the element has a verified map, otherwise the reason text (also for elements the table does not list). */
export function pourbaixUnavailableReason(element: string): string | null {
  const entry = POURBAIX_DATA.elements[element];
  if (!entry) return "No verified data: the species table has no entry for this element.";
  return "reason" in entry ? entry.reason : null;
}

// ---------------------------------------------------------------------------
// Equilibrium port
// ---------------------------------------------------------------------------

/** Per-species affine g_i(pH, E) for one element at a fixed dissolved activity (table order is the tie-break order). */
export function speciesCoefficients(element: string, log10Activity: number): SpeciesCoefficients[] {
  const entry = POURBAIX_DATA.elements[element];
  if (!entry || !("species" in entry)) throw new Error(`No verified ${element}-H2O data: ${pourbaixUnavailableReason(element)}`);
  const h2o = entry.waterDfG_kJ_mol * 1000;
  return entry.species.map((s: PourbaixSpeciesRow) => {
    const m = (2 * s.o - s.h) / s.x;
    const n = (s.z + 2 * s.o - s.h) / s.x;
    const lnA = s.phase === "s" ? 0 : log10Activity * K.ln10;
    return {
      id: s.id, formula: s.formula, phase: s.phase, role: s.role, category: s.category,
      c0: (s.dfG_kJ_mol * 1000 - s.o * h2o + RT * lnA) / s.x,
      cpH: -m * K.ln10 * RT,
      cE: -n * K.faraday_C_mol,
    };
  });
}

/** argmin g_i; the strict < keeps the earlier table row on an exact tie. */
export function dominantSpecies(coeffs: SpeciesCoefficients[], ph: number, e_she: number): SpeciesCoefficients {
  let best = coeffs[0];
  let bestG = best.c0 + best.cpH * ph + best.cE * e_she;
  for (const sp of coeffs) {
    const g = sp.c0 + sp.cpH * ph + sp.cE * e_she;
    if (g < bestG) { best = sp; bestG = g; }
  }
  return best;
}

/** Water lines at 25 °C: E(H+/H2) = -k pH and E(O2/H2O) = 1.2288 - k pH. */
export function waterLines25C(): WaterStabilityLines {
  return {
    herLine: { e_at_ph0: 0, slope: -NERNST_SLOPE_25C },
    oerLine: { e_at_ph0: POURBAIX_DATA.water.e0_O2_H2O_V, slope: -NERNST_SLOPE_25C },
    nernstSlope: NERNST_SLOPE_25C,
  };
}

export function classifyPourbaixPoint(coeffs: SpeciesCoefficients[], ph: number, e_she: number): PourbaixPointState {
  const sp = dominantSpecies(coeffs, ph, e_she);
  const w = waterLines25C();
  return {
    ph, potential_V: e_she, speciesId: sp.id, formula: sp.formula, category: sp.category,
    isInsideWaterStability: e_she >= w.herLine.slope * ph && e_she <= w.oerLine.e_at_ph0 + w.oerLine.slope * ph,
  };
}

/** Sutherland-Hodgman: keep the part of a convex polygon with c + a*pH + b*E <= 0. */
export function clipPolygon(poly: PourbaixPolygon, a: number, b: number, c: number): PourbaixPolygon {
  const out: PourbaixPolygon = [];
  for (let k = 0; k < poly.length; k++) {
    const p = poly[k], q = poly[(k + 1) % poly.length];
    const fp = c + a * p[0] + b * p[1], fq = c + a * q[0] + b * q[1];
    if (fp <= 0) out.push(p);
    if ((fp < 0 && fq > 0) || (fq < 0 && fp > 0)) {
      const t = fp / (fp - fq);
      out.push([p[0] + t * (q[0] - p[0]), p[1] + t * (q[1] - p[1])]);
    }
  }
  return out;
}

export function polygonArea(poly: PourbaixPolygon): number {
  let s = 0;
  for (let k = 0; k < poly.length; k++) { const p = poly[k], q = poly[(k + 1) % poly.length]; s += p[0] * q[1] - q[0] * p[1]; }
  return Math.abs(s) / 2;
}

/** Area centroid of a convex polygon (zone-label anchor). */
export function polygonCentroid(poly: PourbaixPolygon): [number, number] {
  let a = 0, cx = 0, cy = 0;
  for (let k = 0; k < poly.length; k++) {
    const p = poly[k], q = poly[(k + 1) % poly.length];
    const cross = p[0] * q[1] - q[0] * p[1];
    a += cross; cx += (p[0] + q[0]) * cross; cy += (p[1] + q[1]) * cross;
  }
  return a === 0 ? poly[0] : [cx / (3 * a), cy / (3 * a)];
}

export function pointInPolygon(poly: PourbaixPolygon, ph: number, e: number): boolean {
  let inside = false;
  for (let k = 0; k < poly.length; k++) {
    const [x1, y1] = poly[k], [x2, y2] = poly[(k + 1) % poly.length];
    if ((y1 > e) !== (y2 > e) && ph < ((x2 - x1) * (e - y1)) / (y2 - y1) + x1) inside = !inside;
  }
  return inside;
}

/** Exact convex domain of every species that has area in the box pH [-2, 16] x E [-3.0, 2.5] V SHE. */
export function computeDomains(coeffs: SpeciesCoefficients[]): PourbaixDomain[] {
  const domains: PourbaixDomain[] = [];
  for (const sp of coeffs) {
    let poly: PourbaixPolygon = [[BOX.pH_min, BOX.E_min_V_SHE], [BOX.pH_max, BOX.E_min_V_SHE], [BOX.pH_max, BOX.E_max_V_SHE], [BOX.pH_min, BOX.E_max_V_SHE]];
    for (const other of coeffs) {
      if (other === sp) continue;
      poly = clipPolygon(poly, sp.cpH - other.cpH, sp.cE - other.cE, sp.c0 - other.c0);
      if (poly.length === 0) break;
    }
    if (poly.length > 0 && polygonArea(poly) > 1e-9) domains.push({ speciesId: sp.id, formula: sp.formula, category: sp.category, polygon: poly });
  }
  return domains;
}

/** Exact line g_a = g_b of two table species (E = E0 + slope*pH, or a vertical pH line); null when identical. */
export function boundaryLine(coeffs: SpeciesCoefficients[], idA: string, idB: string): PourbaixBoundaryEquation | null {
  const a = coeffs.find((s) => s.id === idA), b = coeffs.find((s) => s.id === idB);
  if (!a || !b) return null;
  const d0 = a.c0 - b.c0, dp = a.cpH - b.cpH, de = a.cE - b.cE;
  if (Math.abs(de) < 1e-9) return Math.abs(dp) < 1e-9 ? null : { type: "vertical", pH: -d0 / dp + 0 };
  return { type: "sloped", E_V_SHE_at_pH0: -d0 / de + 0, slope_V_per_pH: -dp / de + 0 };
}

// ---------------------------------------------------------------------------
// Display helpers (labels and colours only; no thermodynamic rule)
// ---------------------------------------------------------------------------

export const PASSIVATION_NOTE = "thermodynamic domain of a solid oxide/hydroxide (not a kinetic passivity claim)";

export const CATEGORY_STYLE: Record<StabilityCategory, { color: string; alpha: number; legend: string }> = {
  "Immunity": { color: "#38bdf8", alpha: 0.25, legend: "Immunity (metal stable)" },
  "Corrosion (acid)": { color: "#f87171", alpha: 0.22, legend: "Corrosion (acid): cation stable" },
  "Corrosion (alkaline)": { color: "#fb923c", alpha: 0.28, legend: "Corrosion (alkaline): anion stable" },
  "Passivation (thermodynamic, film-forming)": { color: "#10b981", alpha: 0.32, legend: "Passivation (thermodynamic): solid oxide/hydroxide stable" },
  "Transpassive": { color: "#a855f7", alpha: 0.30, legend: "Transpassive: high-valence oxyanion stable" },
};

/** Display text for the engine's riskLevel strings (kept unchanged in the API); no rate or protectiveness claim. */
export const RISK_LEVEL_DISPLAY: Record<string, string> = {
  "Immune": "Metal stable (immunity domain)",
  "Stable Passivity": `Solid oxide/hydroxide stable: ${PASSIVATION_NOTE}`,
  "Severe Corrosion": "Cation stable (acid corrosion domain)",
  "High Risk": "Oxyanion stable (alkaline or transpassive domain)",
  "Caution": "Caution",
  "Pitting Hazard": "Pitting hazard",
};

// ---------------------------------------------------------------------------
// Alloy presets (composition metadata only; the engine has no alloy equilibrium)
// ---------------------------------------------------------------------------

export const DEFAULT_ALLOY_ID = "pure-fe";

export const ALLOY_PRESETS: AlloyPreset[] = [
  {
    id: "inconel-718",
    name: "Inconel 718 (UNS N07718)",
    category: "Nickel Superalloy",
    description: "Precipitation-hardened Ni-Cr superalloy for aerospace turbine disks, rocket nozzles, and sour gas wells. Superb resistance to hot corrosion.",
    composition: { Ni: 53.0, Cr: 19.0, Fe: 18.0, Mo: 3.0, Al: 0.5, Ti: 0.9 },
    recommendedApplication: "Aerospace turbine engines, cryogenic rocket fuel injectors, subsea wellheads.",
  },
  {
    id: "ti-6al-4v",
    name: "Ti-6Al-4V (Grade 5)",
    category: "Titanium Alloy",
    description: "Alpha-beta titanium alloy with outstanding specific strength and spontaneous self-healing TiO2 ceramic passivity across marine and acid environments.",
    composition: { Ti: 90.0, Al: 6.0, V: 4.0, Fe: 0.25 },
    recommendedApplication: "Aerospace airframes, orthopedic implants, offshore seawater piping.",
  },
  {
    id: "al-co-cr-fe-ni-hea",
    name: "AlCoCrFeNi High-Entropy Alloy",
    category: "High-Entropy Alloy (HEA)",
    description: "Equiatomic/near-equiatomic multi-principal element alloy exhibiting cocktail passivation synergy with multi-oxide protective barriers.",
    composition: { Fe: 25.0, Cr: 25.0, Ni: 25.0, Al: 15.0, Mo: 10.0 },
    recommendedApplication: "Nuclear reactor core structures, extreme marine turbines, chemical processing valves.",
  },
  {
    id: "ss-316l",
    name: "Stainless Steel 316L (UNS S31603)",
    category: "Stainless Steel",
    description: "Austenitic Mo-bearing stainless steel with enhanced chloride pitting resistance and low carbon to prevent grain boundary sensitization.",
    composition: { Fe: 68.0, Cr: 17.0, Ni: 12.0, Mo: 2.5, Mn: 2.0 },
    recommendedApplication: "Marine hardware, pharmaceutical vessels, food processing equipment.",
  },
  {
    id: "duplex-2507",
    name: "Super Duplex 2507 (UNS S32750)",
    category: "Stainless Steel",
    description: "50/50 Ferrite-Austenite dual phase super duplex with high Cr and Mo for extreme resistance to chloride stress corrosion cracking.",
    composition: { Fe: 63.0, Cr: 25.0, Ni: 7.0, Mo: 4.0, Cu: 0.5 },
    recommendedApplication: "Offshore oil & gas separators, desalination plants, subsea flowlines.",
  },
  {
    id: "al-7075-t6",
    name: "Aluminum 7075-T6 (Aerospace)",
    category: "Aluminum Alloy",
    description: "Ultra-high strength Zn-Mg-Cu precipitation-hardened aluminum alloy. Sensitive to intergranular corrosion and stress corrosion cracking in chlorides.",
    composition: { Al: 90.0, Cu: 1.6, Fe: 0.5, Cr: 0.2 },
    recommendedApplication: "Aircraft wing spars, military armor plates, high-stress structural fittings.",
  },
  {
    id: "pure-fe",
    name: "Pure Iron / Carbon Steel (Fe)",
    category: "Pure Metal",
    description: "Elemental iron baseline for classic Pourbaix E-pH analysis.",
    composition: { Fe: 100.0 },
    recommendedApplication: "Structural steel baseline, water pipe cathodics.",
  },
  {
    id: "pure-ti",
    name: "Pure Titanium (Grade 2 CP)",
    category: "Pure Metal",
    description: "Commercially pure titanium with high ductility and full seawater immunity.",
    composition: { Ti: 100.0 },
    recommendedApplication: "Chemical heat exchangers, seawater desalination tubing.",
  },
  {
    id: "pure-ni",
    name: "Pure Nickel 200 (Ni)",
    category: "Pure Metal",
    description: "Unalloyed wrought nickel for strong resistance to caustic alkalis.",
    composition: { Ni: 100.0 },
    recommendedApplication: "Caustic evaporator tubes, alkali storage tanks.",
  },
  {
    id: "pure-cr",
    name: "Pure Chromium (Cr)",
    category: "Pure Metal",
    description: "Elemental chromium establishing the benchmark chromia passivation envelope.",
    composition: { Cr: 100.0 },
    recommendedApplication: "Electroplated barrier coatings, superalloy alloying baseline.",
  },
];

/** Element with the highest wt% (first one on a tie); the single element whose M-H2O map a preset is shown with. */
export function primaryElementOf(composition: { [element: string]: number }): string {
  let best = "Fe";
  let bestWt = -1;
  for (const [el, wt] of Object.entries(composition)) {
    if (wt > bestWt) { best = el; bestWt = wt; }
  }
  return best;
}
