"""Contract for the read-only, committed LPBF calibration scorecard view (held-out errors of nuisance-parameter
calibration of the screening melt-pool kernels; screening only, not validation)."""
from module_contract import (
    Authority, Evidence, FORBIDDEN_CLAIM_KEYS, Lifecycle, ModuleContract,
    Operation, Oracle, OWNER_UNASSIGNED, OutputSchema, TestRefs, View,
)


def build_calibration_scorecard_contract(seed):
    return ModuleContract(
        id=seed["id"], version="0.1.0", owner=OWNER_UNASSIGNED,
        workspace=seed["workspace"], label=seed["label"],
        description=seed["description"], next=seed["next"], maturity=seed["scope"],
        navigation="listed", view=View(component=seed["viewComponent"], export=seed["viewExport"]),
        operations=(Operation(
            id="display-scorecard-record", route=None, method=None,
            authority=Authority(kind="browser-local", exception_reason=
                "Read-only committed JSON display; the record is generated by python/tools/lpbf_calibration_fit.py "
                "and no solver or server operation runs in this view."),
            undeclared_input=("document",),
            output=OutputSchema(fields=("headline", "n01", "regimeConfusion", "coverage", "unresolved", "honesty"),
                                status_key=None),
        ),),
        evidence=Evidence(emits=(), ceiling="screening-only", forbidden_claims=FORBIDDEN_CLAIM_KEYS,
            note="No numerical oracle is declared for this view. Held-out errors of nuisance-parameter calibration "
                 "are displayed from the committed record; the page proposes no evidence-label promotion and the "
                 "calibrated mode it describes stays screening only (not validation)."),
        tests=TestRefs(oracle=Oracle(status="pending"),
                      schema="python/test_module_contract_calibration_scorecard.py",
                      docs="docs/modules/lpbf-calibration-scorecard.md"),
        migration_state="contracted", lifecycle=Lifecycle(background_work="none"),
        legacy_notes=(
            "The operation describes a local view, not a request/response endpoint. Output fields name consumed "
            "record sections; the nested document is undeclaredInput, validated at runtime by "
            "checkedCalibrationScorecard.",
            "Vite eagerly bundles the newest committed docs/LPBF_CALIBRATION_SCORECARD_*.view.json. An absent record "
            "produces NoScorecardRecord; malformed committed bytes throw during checkedCalibrationScorecard rather "
            "than producing an empty success.",
            "No fetch, solver, timer, worker or archive mutation runs in this module. The Guo N01 sentinel card is "
            "always rendered; error statistics, intervals, hashes and gate statuses are read from JSON.",
            "The gate status of a cell decides whether the opt-in calibrated mode may serve it. While no cell is "
            "enabled the Melt Pool lab shows no calibrated-mode control at all; the evidence label of every result "
            "stays screening only.",
        ),
        source_refs=(
            "src/data/lpbfCalibrationScorecardRecord.ts",
            "src/data/lpbfCalibrationScorecard.ts::checkedCalibrationScorecard",
            "src/components/LpbfCalibrationScorecardLab.tsx::LpbfCalibrationScorecardLab",
            "src/components/LpbfCalibrationScorecardLab.tsx::NoScorecardRecord",
            "src/components/LpbfCalibrationScorecardLab.tsx::N01Card",
            "tests/lpbf-calibration-scorecard.test.tsx",
        ),
        seed_derived=("label", "description", "next", "maturity"),
    )
