#!/usr/bin/env python3
"""
MetalliX Persistent Python HPC Microservice & IPC Worker Daemon
Maintains scientific calculation modules warm in memory, bypassing Python startup & module import overhead.
Exposes:
 1. UNIX Domain Socket IPC (POSIX) in a private 0700 directory for direct Node.js streaming.
 2. Loopback HTTP Microservice on an ephemeral port: always on Windows (no UNIX socket there), on
    POSIX only when METALLIX_IPC_HTTP=1.
Both channels and their actual address are announced in the ready message on stdout; the Node
supervisor (server/processOrchestrator.ts) only talks to channels its own child announced.

Security model (both channels, protocol "metallix-ipc-v2"):
 - The per-spawn shared secret METALLIX_IPC_TOKEN (>= 32 chars, generated by the Node supervisor,
   passed through the environment) never travels on the wire. A request's MAC covers method, path,
   timestamp, nonce, body length and SHA-256(body) and is verified from the headers BEFORE any body
   byte is read; the body is then streamed and must match the hash. Each response carries
   HMAC(token, nonce, status, length, SHA-256(body)). A listener without the token can neither
   reuse a request (nonce replay cache, +-120 s window) nor forge a response the client accepts.
 - Unauthenticated connections are bounded: at most PREAUTH_SLOTS at a time, each with a
   PREAUTH_DEADLINE_S deadline for the request line and headers; one request per connection.
 - The service refuses to start without a token, before any warm-up.
 - HTTP: no CORS headers; requests with an ``Origin`` header (browsers) are rejected; ``Host`` must
   name the bound loopback address and port (DNS rebinding); POST bodies must be
   ``application/json`` and at most MAX_BODY_BYTES. Windows binds with SO_EXCLUSIVEADDRUSE.
 - Scripts: only ``python/<name>.py`` or ``<name>.py`` where <name> is in ALLOWED_SCRIPT_NAMES,
   resolved with realpath and required to stay in SCRIPT_DIR.
 - The UNIX socket lives in a fresh 0700 directory (mkdtemp, under XDG_RUNTIME_DIR when set) and
   is created 0600; on POSIX a socket that cannot be created is fatal, not a silent HTTP-only mode.
 - Only loopback addresses are bound (127.0.0.0/8, localhost, ::1); anything else is refused.
 - With METALLIX_IPC_STDIN_WATCH=1 the daemon exits (and removes its socket directory) when its
   stdin reaches EOF, i.e. when the supervising Node process is gone.
"""

import sys
import os
import io
import re
import hmac
import hashlib
import ipaddress
import json
import multiprocessing
import shutil
import stat
import tempfile
import time
import socket
import socketserver
import http.server
import threading
import traceback
import signal
from concurrent.futures import CancelledError, ProcessPoolExecutor, TimeoutError
from concurrent.futures.process import BrokenProcessPool
from typing import Dict, Any, Optional, Iterable, Tuple

# Add script directory to sys.path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if SCRIPT_DIR not in sys.path:
    sys.path.insert(0, SCRIPT_DIR)

# Explicit socket path (optional). Unset: a private 0700 directory is created at start.
UNIX_SOCKET_PATH: Optional[str] = os.environ.get("METALLIX_IPC_SOCK") or None
HTTP_PORT = int(os.environ.get("METALLIX_IPC_PORT", "0") or "0")
HTTP_HOST = os.environ.get("METALLIX_IPC_HOST", "127.0.0.1")
# HTTP is the only channel on Windows; on POSIX the UNIX socket is enough unless HTTP is asked for.
HTTP_ENABLED = os.name == "nt" or os.environ.get("METALLIX_IPC_HTTP", "") == "1"
STDIN_WATCH = os.environ.get("METALLIX_IPC_STDIN_WATCH", "") == "1"
MIN_TOKEN_LENGTH = 32


def _token_taker():
    """Removes METALLIX_IPC_TOKEN from os.environ at import, before any worker pool exists, so
    pool workers and the solvers they run never see it in their environment. The value is held
    in this closure (not a module global) until run_services takes it once and hands it to the
    server objects. Solver code that runs in this process (the in-process fallback) could still
    find it in memory, so this is environment/global hygiene, not an isolation boundary."""
    held = [os.environ.pop("METALLIX_IPC_TOKEN", None)]

    def take() -> Optional[str]:
        value, held[0] = held[0], None
        return value

    return take


_take_ipc_token = _token_taker()
del _token_taker

# Number of parallel workers (defaults to CPU count clamped between 2 and 4)
DEFAULT_WORKERS = max(2, min(4, (os.cpu_count() or 2)))
NUM_WORKERS = int(os.environ.get("METALLIX_IPC_WORKERS", DEFAULT_WORKERS))

# List of scientific modules to keep warm in memory
WARM_MODULE_NAMES = [
    "calphad_solver",
    "dft_property_calculator",
    "cnls_fitting_solver",
    "xrd_peak_deconvolution",
    "lpbf_thermal_solver",
    "pourbaix_solver",
    "battery_corrosion_eis_solver",
    "kinetics_ttt_cct_solver",
    "icme_multiscale_pipeline_solver",
    "stochastic_uq_mmpds_solver",
    "stl_slicer_build_time_solver",
    "lpbf_build_job_solver",
    "tafel_corrosion_rate_solver",
]

# Scripts the service may execute: exactly the scripts routes/*.ts dispatch through
# runPythonScript. Warm-only modules (imported for speed, never dispatched), tools, tests and
# this service itself are refused. test_persistent_ipc_security requires this set to equal the
# literal script paths in routes/*.ts in both directions, so a stale entry fails the test.
ALLOWED_SCRIPT_NAMES = frozenset({
    "battery_corrosion_eis_solver",
    "calphad_solver",
    "dft_property_calculator",
    "icme_multiscale_pipeline_solver",
    "kinetics_ttt_cct_solver",
    "lpbf_bayesian_optimizer",
    "lpbf_calibrated_meltpool",
    "lpbf_thermal_solver",
    "micrograph_measure",
    "pourbaix_solver",
    "stl_slicer_build_time_solver",
    "stochastic_uq_mmpds_solver",
    "tafel_corrosion_rate_solver",
    "xrd_peak_deconvolution",
})

# Scripts served by their own single-worker pool. Their per-process caches (calphad_model_cache:
# the compiled pycalphad models) are then always in the process that serves the next request for
# that script, and only that one process holds them (a shared-pool worker would be picked at
# random, so up to NUM_WORKERS cold builds and copies per system). Requests for such a script run
# one at a time through an _AffinityLane (queue, supersede, budget). Metadata requests
# (METADATA_ACTIONS) go to the shared pool and never wait behind a calculation.
# METALLIX_IPC_AFFINITY=0 sends everything to the shared pool instead.
AFFINITY_SCRIPT_NAMES = (frozenset({"calphad_solver"})
                         if os.environ.get("METALLIX_IPC_AFFINITY", "1") != "0" else frozenset())
METADATA_ACTIONS = frozenset({"list_databases"})
MAX_SUPERSEDE_KEY_LENGTH = 128


def _payload_field(payload: Any, key: str) -> Any:
    """A top-level field of a JSON-object payload (dict or JSON text), else None."""
    if isinstance(payload, str):
        try:
            payload = json.loads(payload)
        except ValueError:
            return None
    return payload.get(key) if isinstance(payload, dict) else None


def _supersede_key(payload: Any) -> Optional[str]:
    key = _payload_field(payload, "supersedeKey")
    if isinstance(key, str) and 0 < len(key) <= MAX_SUPERSEDE_KEY_LENGTH:
        return key
    return None

_SCRIPT_FILE_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\.py\Z")
MAX_SCRIPT_ARGS = 64
MAX_TIMEOUT_MS = 600000


class IPCRequestRejected(Exception):
    """A request refused before any script runs; ``status`` is the HTTP status to send."""

    def __init__(self, status: int, code: str, message: str):
        super().__init__(message)
        self.status = status
        self.code = code
        self.message = message

    def as_result(self) -> Dict[str, Any]:
        return {"stdout": "", "stderr": self.message, "exitCode": 1, "error": self.message,
                "code": self.code, "status": self.status}


def _same_dir(a: str, b: str) -> bool:
    return os.path.normcase(os.path.normpath(a)) == os.path.normcase(os.path.normpath(b))


def resolve_script_path(script_dir: str, script: Any,
                        allowed: Iterable[str] = ALLOWED_SCRIPT_NAMES) -> str:
    """Map a request's script reference to an allowlisted file directly inside script_dir.

    Accepted forms are exactly ``python/<name>.py`` and ``<name>.py``. Traversal, absolute
    paths, drive letters, UNC paths, backslashes and nested directories are refused (400);
    names outside the allowlist and symlinks resolving outside script_dir are refused (403).
    """
    if not isinstance(script, str) or not script.strip():
        raise IPCRequestRejected(400, "MISSING_SCRIPT", "Missing script path")
    ref = script.strip()
    if len(ref) > 200 or any(ch in ref for ch in ("\\", ":", "\x00")) or ref.startswith("/"):
        raise IPCRequestRejected(400, "INVALID_SCRIPT_PATH", "Invalid script path")
    parts = ref.split("/")
    if len(parts) == 2 and parts[0] == "python":
        file_name = parts[1]
    elif len(parts) == 1:
        file_name = parts[0]
    else:
        raise IPCRequestRejected(400, "INVALID_SCRIPT_PATH", "Invalid script path")
    if not _SCRIPT_FILE_RE.match(file_name):
        raise IPCRequestRejected(400, "INVALID_SCRIPT_PATH", "Invalid script path")
    if file_name[:-3] not in allowed:
        raise IPCRequestRejected(403, "SCRIPT_NOT_ALLOWED", f"Script not allowed: {file_name}")
    base = os.path.realpath(script_dir)
    full_path = os.path.realpath(os.path.join(base, file_name))
    if not _same_dir(os.path.dirname(full_path), base):
        raise IPCRequestRejected(403, "SCRIPT_OUTSIDE_SCRIPT_DIR",
                                 f"Script resolves outside the scripts directory: {file_name}")
    if not os.path.isfile(full_path):
        raise IPCRequestRejected(404, "SCRIPT_NOT_FOUND", f"Script not found: {script}")
    return full_path


def validate_exec_request(req: Any) -> Tuple[Any, Any, list, int]:
    """Shape checks shared by both channels; returns (script, payload, args, timeout_ms)."""
    if not isinstance(req, dict):
        raise IPCRequestRejected(400, "INVALID_REQUEST", "Request body must be a JSON object")
    args = req.get("args", [])
    if args is None:
        args = []
    if (not isinstance(args, list) or len(args) > MAX_SCRIPT_ARGS
            or not all(isinstance(a, str) for a in args)):
        raise IPCRequestRejected(400, "INVALID_ARGS", "args must be a list of strings")
    timeout_ms = req.get("timeoutMs", 15000)
    if isinstance(timeout_ms, bool) or not isinstance(timeout_ms, (int, float)) \
            or not (0 < timeout_ms <= MAX_TIMEOUT_MS):
        raise IPCRequestRejected(400, "INVALID_TIMEOUT", f"timeoutMs must be in (0, {MAX_TIMEOUT_MS}]")
    return req.get("script", ""), req.get("payload"), args, int(timeout_ms)


# --- Mutual authentication (metallix-ipc-v2) --------------------------------------------
PROTOCOL = b"metallix-ipc-v2"
MAX_CLOCK_SKEW_MS = 120_000
MAX_BODY_BYTES = 64 * 1024 * 1024  # server.ts accepts 50 MB JSON bodies
NONCE_CACHE_MAX = 100_000
_NONCE_RE = re.compile(r"[0-9a-f]{32}\Z")
_HEX64_RE = re.compile(r"[0-9a-f]{64}\Z")
_TS_RE = re.compile(r"[0-9]{1,16}\Z")


def _hmac_hex(token: str, message: bytes) -> str:
    return hmac.new(token.encode("utf-8"), message, hashlib.sha256).hexdigest()


def body_digest(body: bytes) -> str:
    return hashlib.sha256(body).hexdigest()


def request_mac(token: str, method: str, path: str, ts: str, nonce: str, length: int, digest: str) -> str:
    """HMAC over protocol, direction, method, path, timestamp, nonce, body length and SHA-256(body).

    Everything it covers is known from the request head, so it is verified before the body is read.
    """
    msg = "\n".join([PROTOCOL.decode("ascii"), "req", method, path, ts, nonce, str(int(length)), digest])
    return _hmac_hex(token, msg.encode("utf-8"))


def response_mac(token: str, nonce: str, status: int, length: int, digest: str) -> str:
    """HMAC binding a response to the request nonce, so a non-owner cannot forge solver output."""
    msg = "\n".join([PROTOCOL.decode("ascii"), "resp", nonce, str(int(status)), str(int(length)), digest])
    return _hmac_hex(token, msg.encode("ascii"))


def macs_equal(presented: Any, expected: str) -> bool:
    """Constant-time comparison of hex MACs."""
    if not isinstance(presented, str) or not _HEX64_RE.match(presented):
        return False
    return hmac.compare_digest(presented.encode("ascii"), expected.encode("ascii"))


class NonceCache:
    """Remembers authenticated nonces for longer than any timestamp stays acceptable.

    A request is accepted while |now - ts| <= MAX_CLOCK_SKEW_MS, i.e. for at most 2 * skew after
    it is first seen (ts at the +skew edge). Entries live 2 * skew + 1 ms and a nonce is a replay
    while now <= expiry, so a replay at exactly first-seen + 2 * skew is still refused.
    """

    def __init__(self, ttl_ms: int = 2 * MAX_CLOCK_SKEW_MS + 1, max_entries: int = NONCE_CACHE_MAX):
        self.ttl_ms = ttl_ms
        self.max_entries = max_entries
        self._seen: Dict[str, int] = {}
        self._lock = threading.Lock()

    def add_if_new(self, nonce: str, now_ms: int) -> bool:
        with self._lock:
            if len(self._seen) >= self.max_entries:
                self._seen = {n: exp for n, exp in self._seen.items() if exp >= now_ms}
                if len(self._seen) >= self.max_entries:
                    return False  # fail closed under a nonce flood
            if nonce in self._seen and self._seen[nonce] >= now_ms:
                return False
            self._seen[nonce] = now_ms + self.ttl_ms
            return True


def _now_ms() -> int:
    return int(time.time() * 1000)


def check_auth_fields(ts: Any, nonce: Any, mac: Any, digest: Any,
                      now_ms: Optional[int] = None) -> Tuple[str, str, str, str]:
    """Shape and freshness checks of the authentication fields."""
    if not (isinstance(ts, str) and _TS_RE.match(ts) and isinstance(nonce, str) and _NONCE_RE.match(nonce)
            and isinstance(mac, str) and _HEX64_RE.match(mac)
            and isinstance(digest, str) and _HEX64_RE.match(digest)):
        raise IPCRequestRejected(401, "UNAUTHORIZED", "Missing or malformed IPC authentication")
    now = _now_ms() if now_ms is None else now_ms
    if abs(now - int(ts)) > MAX_CLOCK_SKEW_MS:
        raise IPCRequestRejected(401, "STALE_REQUEST", "IPC request timestamp outside the allowed window")
    return ts, nonce, mac, digest


def verify_request(token: Optional[str], method: str, path: str, ts: Any, nonce: Any, mac: Any,
                   length: int, digest: Any, nonces: "NonceCache", now_ms: Optional[int] = None) -> None:
    """Raise 401 unless mac authenticates this request head (incl. body length and hash) and the
    nonce is unused. Needs no body byte. The nonce is recorded only after the MAC verifies, so
    unauthenticated traffic cannot fill the replay cache. Fails closed without a token."""
    now = _now_ms() if now_ms is None else now_ms
    check_auth_fields(ts, nonce, mac, digest, now)
    if not token or not macs_equal(mac, request_mac(token, method, path, ts, nonce, length, digest)):
        raise IPCRequestRejected(401, "UNAUTHORIZED", "Missing or invalid IPC authentication")
    if not nonces.add_if_new(nonce, now):
        raise IPCRequestRejected(401, "REPLAYED_REQUEST", "IPC request nonce was already used")


def read_body_checked(read, length: int, digest: str, deadline: float, chunk: int = 64 * 1024) -> bytes:
    """Streams exactly `length` bytes through `read(n)` (already authenticated head) and checks the
    SHA-256. Memory grows with bytes actually received, never with the declared length."""
    buf = bytearray()
    h = hashlib.sha256()
    while len(buf) < length:
        if time.monotonic() > deadline:
            raise IPCRequestRejected(408, "REQUEST_TIMEOUT", "IPC request body not received in time")
        part = read(min(chunk, length - len(buf)))
        if not part:
            raise IPCRequestRejected(400, "TRUNCATED_BODY", "IPC request body ended early")
        h.update(part)
        buf += part
    if not hmac.compare_digest(h.hexdigest(), digest):
        raise IPCRequestRejected(400, "BODY_HASH_MISMATCH", "IPC request body does not match its hash")
    return bytes(buf)


def is_loopback_host(host: str) -> bool:
    if host.strip().lower() == "localhost":
        return True
    try:
        return ipaddress.ip_address(host.strip().strip("[]")).is_loopback
    except ValueError:
        return False


def allowed_host_headers(bind_host: str, port: int) -> frozenset:
    """Host header values accepted by the HTTP service (anything else: DNS rebinding)."""
    hosts = {f"127.0.0.1:{port}", f"localhost:{port}", f"[::1]:{port}"}
    h = bind_host.strip().lower()
    hosts.add(f"[{h.strip('[]')}]:{port}" if ":" in h.strip("[]") else f"{h}:{port}")
    return frozenset(hosts)


def _single_header(headers: Any, name: str) -> Optional[str]:
    values = headers.get_all(name) or []
    return values[0].strip() if len(values) == 1 else None


def check_http_headers(headers: Any, *, allowed_hosts: Iterable[str], require_json: bool,
                       now_ms: Optional[int] = None) -> Tuple[str, str, str, str]:
    """Host, Origin, auth-field and Content-Type checks; returns (ts, nonce, mac, body digest).

    The MAC is verified next (verify_request) from the head alone, before the body is read.
    """
    host = _single_header(headers, "Host")
    if host is None or host.lower() not in allowed_hosts:
        raise IPCRequestRejected(403, "HOST_NOT_ALLOWED", "Host header not allowed")
    if headers.get("Origin") is not None:
        raise IPCRequestRejected(403, "ORIGIN_NOT_ALLOWED", "Browser-originated requests are not allowed")
    auth = check_auth_fields(_single_header(headers, "X-Metallix-Ts"), _single_header(headers, "X-Metallix-Nonce"),
                             _single_header(headers, "X-Metallix-Mac"),
                             _single_header(headers, "X-Metallix-Body-Sha256"), now_ms)
    if require_json:
        media_type = (headers.get("Content-Type") or "").split(";", 1)[0].strip().lower()
        if media_type != "application/json":
            raise IPCRequestRejected(415, "UNSUPPORTED_MEDIA_TYPE", "Content-Type must be application/json")
    return auth


def validate_startup_config(host: str, token: Optional[str]) -> None:
    """Refuse to serve without a usable token or on anything but a loopback address."""
    if not token or len(token) < MIN_TOKEN_LENGTH:
        raise SystemExit(
            f"[PersistentIPC] Refusing to start: METALLIX_IPC_TOKEN must be set (>= {MIN_TOKEN_LENGTH} "
            "characters). The Node supervisor generates it; set it yourself when launching by hand.")
    if not is_loopback_host(host):
        raise SystemExit(
            f"[PersistentIPC] Refusing to bind METALLIX_IPC_HOST={host!r}: only loopback addresses "
            "(127.0.0.1, localhost, ::1) are allowed; the IPC service has no remote clients.")

# =========================================================================
# Worker Subprocess Routines (Run in isolated multi-core processes)
# =========================================================================
_worker_compiled_cache: Dict[str, Any] = {}
_worker_modules: Dict[str, Any] = {}


def _exit_when_parent_dies() -> None:
    """Pool workers end when their parent (the daemon) is gone, also after a hard kill of the
    daemon (which would otherwise leave them running, each holding its imports and caches)."""
    parent = multiprocessing.parent_process()
    if parent is None:
        return

    def watch():
        try:
            parent.join()
        except Exception:
            return
        os._exit(0)

    threading.Thread(target=watch, daemon=True, name="metallix-worker-parent-watch").start()


def _worker_init(script_dir: str, module_names: list):
    """Initializes each process pool worker by adding paths and pre-warming modules."""
    _exit_when_parent_dies()
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)
    global _worker_modules, _worker_compiled_cache
    _worker_modules = {}
    _worker_compiled_cache = {}

    for mod_name in module_names:
        # realpath: the key execute_script submits (resolve_script_path returns realpaths).
        py_file = os.path.realpath(os.path.join(script_dir, f"{mod_name}.py"))
        try:
            mod = __import__(mod_name)
            _worker_modules[mod_name] = mod
            if os.path.exists(py_file):
                with open(py_file, "r", encoding="utf-8") as f:
                    _worker_compiled_cache[py_file] = compile(f.read(), py_file, "exec")
        except Exception:
            pass


def _worker_run_script(full_path: str, input_str: str, args: list) -> Dict[str, Any]:
    """
    Executes a script inside an isolated worker process.
    Guarantees independent sys.stdin / sys.stdout / sys.stderr and full CPU concurrency.
    """
    global _worker_compiled_cache

    if full_path not in _worker_compiled_cache:
        try:
            with open(full_path, "r", encoding="utf-8") as f:
                _worker_compiled_cache[full_path] = compile(f.read(), full_path, "exec")
        except Exception as e:
            return {
                "stdout": "",
                "stderr": f"Compilation failed: {str(e)}",
                "exitCode": 1,
            }

    compiled = _worker_compiled_cache[full_path]

    old_stdin = sys.stdin
    old_stdout = sys.stdout
    old_stderr = sys.stderr
    old_argv = sys.argv

    captured_stdout = io.StringIO()
    captured_stderr = io.StringIO()
    sys.stdin = io.StringIO(input_str)
    sys.stdout = captured_stdout
    sys.stderr = captured_stderr
    sys.argv = [os.path.basename(full_path)] + (args or [])

    env = {
        "__name__": "__main__",
        "__file__": full_path,
        "__package__": None,
    }

    exit_code = 0
    try:
        exec(compiled, env)
    except SystemExit as se:
        exit_code = se.code if isinstance(se.code, int) else 0
    except Exception:
        exit_code = 1
        captured_stderr.write(traceback.format_exc())
    finally:
        sys.stdin = old_stdin
        sys.stdout = old_stdout
        sys.stderr = old_stderr
        sys.argv = old_argv

    return {
        "stdout": captured_stdout.getvalue(),
        "stderr": captured_stderr.getvalue(),
        "exitCode": exit_code,
    }


def _worker_noop(delay: float) -> int:
    """Pre-warm task: makes the pool start (and initialise) its worker processes."""
    time.sleep(delay)
    return os.getpid()


_MP_CONTEXT = None


def _pool_mp_context():
    """Workers start from a fresh interpreter instead of a fork of this process (whose memory holds
    the token). POSIX: forkserver, preloaded with this script (guarded, no registry) and the warm
    modules, so every worker shares those imports copy-on-write; the forkserver itself is started
    from the already-scrubbed environment. Windows: spawn (each worker imports in _worker_init)."""
    global _MP_CONTEXT
    if _MP_CONTEXT is None:
        if os.name != "nt" and "forkserver" in multiprocessing.get_all_start_methods():
            ctx = multiprocessing.get_context("forkserver")
            preload = (["__main__"] if __name__ == "__main__" else []) + list(WARM_MODULE_NAMES)
            ctx.set_forkserver_preload(preload)
            _MP_CONTEXT = ctx
        else:
            _MP_CONTEXT = multiprocessing.get_context("spawn")
    return _MP_CONTEXT


class _AffinityTicket:
    __slots__ = ("key", "superseded")

    def __init__(self, key: Optional[str]):
        self.key = key
        self.superseded = False


class _AffinityLane:
    """Serial dispatcher for one affinity script.

    At most ONE job is inside the lane's single-worker pool at any time; waiting requests stay in
    this lane's own queue, where they can be superseded (a newer request with the same
    supersedeKey, e.g. the next slider position from the same Studio) or time out without ever
    running. Consequences, by construction:
      * a request that times out while queued is never computed later (no zombie jobs);
      * the running job is the only work in the pool, so when it exceeds its caller's budget the
        worker is killed and replaced immediately, whatever else is queued (a hung pycalphad call
        cannot block the lane);
      * a worker death affects only the one running request.
    Recycling is generation-aware: a handler replaces the pool only if it is still the pool its job
    ran in, so a stale handler never kills a replacement.
    ``submit_args`` is (callable, *args) for the pool; tests pass a thread pool factory.
    """

    def __init__(self, name: str, factory, prestart_args: Optional[tuple] = None):
        self.name = name
        self._factory = factory
        self._prestart_args = prestart_args
        self.cond = threading.Condition()
        self.pool = None
        self.generation = 0
        self.waiting: list = []
        self.running: Optional[_AffinityTicket] = None
        self.stats = {"completed": 0, "superseded": 0, "queueTimeouts": 0, "runTimeouts": 0,
                      "workerDeaths": 0, "recycles": 0}

    # -- pool management (callers hold no lock; these take it) --
    def _ensure_pool(self):
        with self.cond:
            if self.pool is None:
                self.pool = self._factory()
                self.generation += 1
                if self._prestart_args is not None:
                    try:
                        self.pool.submit(*self._prestart_args)
                    except Exception:
                        pass
            return self.pool, self.generation

    def recycle(self, generation: int) -> bool:
        """Kill the pool of ``generation`` and start a replacement; no-op if it was already replaced."""
        with self.cond:
            if self.pool is None or generation != self.generation:
                return False
            old, self.pool = self.pool, None
            self.stats["recycles"] += 1
        ConcurrentModuleRegistry._kill_pool(old)
        self._ensure_pool()  # replacement starts now, not on the next request
        return True

    def prestart(self) -> None:
        self._ensure_pool()

    def shutdown(self) -> None:
        with self.cond:
            old, self.pool = self.pool, None
            self.generation += 1
            self.cond.notify_all()
        if old is not None:
            ConcurrentModuleRegistry._kill_pool(old)

    def snapshot(self) -> Dict[str, Any]:
        with self.cond:
            return {"queued": sum(1 for t in self.waiting if not t.superseded),
                    "running": self.running is not None, "generation": self.generation, **self.stats}

    # -- one request --
    def run(self, submit_args: tuple, timeout_s: float, key: Optional[str]) -> Dict[str, Any]:
        t0 = time.perf_counter()
        deadline = t0 + timeout_s
        ticket = _AffinityTicket(key)
        with self.cond:
            if key is not None:
                for other in self.waiting:
                    if other.key == key and not other.superseded:
                        other.superseded = True
                        self.stats["superseded"] += 1
            self.waiting.append(ticket)
            self.cond.notify_all()
            while True:
                if ticket.superseded:
                    self.waiting.remove(ticket)
                    self.cond.notify_all()
                    return {"outcome": "superseded", "queueWaitMs": _ms_since(t0)}
                head = next((t for t in self.waiting if not t.superseded), None)
                if self.running is None and head is ticket:
                    break
                remaining = deadline - time.perf_counter()
                if remaining <= 0:
                    ahead = sum(1 for t in self.waiting[: self.waiting.index(ticket)] if not t.superseded)
                    ahead += 1 if self.running is not None else 0
                    self.waiting.remove(ticket)
                    self.stats["queueTimeouts"] += 1
                    self.cond.notify_all()
                    return {"outcome": "queue-timeout", "ahead": ahead, "queueWaitMs": _ms_since(t0)}
                self.cond.wait(remaining)
            self.waiting.remove(ticket)
            self.running = ticket
        queue_ms = _ms_since(t0)
        try:
            pool, generation = self._ensure_pool()
            try:
                future = pool.submit(*submit_args)
            except (BrokenProcessPool, RuntimeError):
                # not submitted, so not executed: replace the pool and submit once more
                self.recycle(generation)
                pool, generation = self._ensure_pool()
                future = pool.submit(*submit_args)
            try:
                res = future.result(timeout=max(0.001, deadline - time.perf_counter()))
            except TimeoutError:
                with self.cond:
                    self.stats["runTimeouts"] += 1
                self.recycle(generation)
                return {"outcome": "run-timeout", "queueWaitMs": queue_ms}
            except (BrokenProcessPool, CancelledError):
                with self.cond:
                    self.stats["workerDeaths"] += 1
                self.recycle(generation)
                return {"outcome": "worker-died", "queueWaitMs": queue_ms}
            with self.cond:
                self.stats["completed"] += 1
            return {"outcome": "ok", "result": res, "queueWaitMs": queue_ms}
        finally:
            with self.cond:
                self.running = None
                self.cond.notify_all()


def _ms_since(t0: float) -> float:
    return round((time.perf_counter() - t0) * 1000.0, 2)


class ConcurrentModuleRegistry:
    """
    Manages warm module imports, pre-compilation, and a high-concurrency ProcessPoolExecutor
    to execute scientific metallurgy & physics computations in parallel across all CPU cores.
    """

    def __init__(self, script_dir: str, num_workers: int = NUM_WORKERS):
        self.script_dir = script_dir
        self.num_workers = num_workers
        self.modules: Dict[str, Any] = {}
        self.compiled_code: Dict[str, Any] = {}
        self.import_times: Dict[str, float] = {}
        self.stats_lock = threading.Lock()
        self.fallback_lock = threading.Lock()
        self.request_count = 0
        self.active_jobs = 0
        self.total_duration_ms = 0.0
        self.start_time = time.time()
        self.pool: Optional[ProcessPoolExecutor] = None
        # One serial lane (single-worker pool + queue) per AFFINITY_SCRIPT_NAMES entry, created on
        # first use or by start_affinity_pools.
        self.affinity_lanes: Dict[str, _AffinityLane] = {}
        self.affinity_lock = threading.Lock()

        self.warmup()
        self._init_pool()

    def warmup(self):
        """Eagerly imports all modules and compiles their source code in master process."""
        sys.stderr.write("[PersistentIPC] Warming up scientific modules in memory...\n")
        t0 = time.time()
        for mod_name in WARM_MODULE_NAMES:
            py_file = os.path.realpath(os.path.join(self.script_dir, f"{mod_name}.py"))
            t_mod0 = time.time()
            try:
                mod = __import__(mod_name)
                self.modules[mod_name] = mod
                if os.path.exists(py_file):
                    with open(py_file, "r", encoding="utf-8") as f:
                        code_str = f.read()
                    compiled = compile(code_str, py_file, "exec")
                    self.compiled_code[py_file] = compiled
                    self.compiled_code[f"python/{mod_name}.py"] = compiled
                    self.compiled_code[f"{mod_name}.py"] = compiled

                dt = (time.time() - t_mod0) * 1000.0
                self.import_times[mod_name] = round(dt, 2)
            except Exception as e:
                sys.stderr.write(f"[PersistentIPC] Warning: Failed to pre-warm {mod_name}: {e}\n")

        total_dt = (time.time() - t0) * 1000.0
        sys.stderr.write(
            f"[PersistentIPC] Successfully loaded {len(self.modules)} modules into RAM in {total_dt:.1f}ms\n"
        )

    def _init_pool(self):
        """Spawns or recycles the multi-process worker pool."""
        try:
            if self.pool:
                try:
                    self.pool.shutdown(wait=False, cancel_futures=True)
                except Exception:
                    pass
            self.pool = ProcessPoolExecutor(
                max_workers=self.num_workers,
                mp_context=_pool_mp_context(),
                initializer=_worker_init,
                initargs=(self.script_dir, WARM_MODULE_NAMES),
            )
            sys.stderr.write(
                f"[PersistentIPC] ProcessPoolExecutor initialized with {self.num_workers} warm worker processes.\n"
            )
        except Exception as e:
            sys.stderr.write(f"[PersistentIPC] Worker pool creation error: {e}\n")
            self.pool = None

    def _affinity_name(self, full_path: str) -> Optional[str]:
        name = os.path.splitext(os.path.basename(full_path))[0]
        return name if name in AFFINITY_SCRIPT_NAMES else None

    def _new_affinity_pool(self, name: str) -> ProcessPoolExecutor:
        return ProcessPoolExecutor(
            max_workers=1,
            mp_context=_pool_mp_context(),
            initializer=_worker_init,
            initargs=(self.script_dir, [name]),
        )

    def _affinity_lane(self, name: str) -> _AffinityLane:
        with self.affinity_lock:
            lane = self.affinity_lanes.get(name)
            if lane is None:
                lane = _AffinityLane(name, lambda: self._new_affinity_pool(name), (_worker_noop, 0.0))
                self.affinity_lanes[name] = lane
            return lane

    def start_affinity_pools(self) -> None:
        """Starts the affinity workers in the background (no wait), so the first request does not
        pay for the process start and imports."""
        for name in sorted(AFFINITY_SCRIPT_NAMES):
            try:
                self._affinity_lane(name).prestart()
            except Exception as e:
                sys.stderr.write(f"[PersistentIPC] Affinity pre-start failed for {name}: {e}\n")

    @staticmethod
    def _kill_pool(pool) -> None:
        procs = list((getattr(pool, "_processes", None) or {}).values())
        try:
            pool.shutdown(wait=False, cancel_futures=True)
        except Exception:
            pass
        for proc in procs:
            try:
                proc.terminate()
            except Exception:
                pass

    def _execute_affinity(self, name: str, full_path: str, input_str: str, args: list, timeout_ms: Any,
                          timeout_sec: float, payload: Any, start_time: float) -> Dict[str, Any]:
        lane = self._affinity_lane(name)
        with self.stats_lock:
            self.active_jobs += 1
        try:
            out = lane.run((_worker_run_script, full_path, input_str, args), timeout_sec, _supersede_key(payload))
        finally:
            with self.stats_lock:
                self.active_jobs = max(0, self.active_jobs - 1)
        duration_ms = round((time.perf_counter() - start_time) * 1000.0, 2)
        base = {"durationMs": duration_ms, "warm": True, "concurrency": f"affinity_pool:{name}",
                "queueWaitMs": out["queueWaitMs"]}
        outcome = out["outcome"]
        if outcome == "ok":
            res = out["result"]
            with self.stats_lock:
                self.request_count += 1
                self.total_duration_ms += duration_ms
            return {"stdout": res["stdout"], "stderr": res["stderr"], "exitCode": res["exitCode"], **base}
        if outcome == "superseded":
            # Not an error of the request: a newer request from the same client replaced it before it
            # started. Answered as an explicit, number-free envelope.
            envelope = {"success": False, "status": "superseded",
                        "reason": "superseded by a newer request with the same supersedeKey before it started; "
                                  "not computed"}
            return {"stdout": json.dumps(envelope), "stderr": "", "exitCode": 0, "superseded": True, **base}
        if outcome == "queue-timeout":
            msg = (f"Execution timed out after {timeout_ms}ms (never started: {out['ahead']} {name} job(s) "
                   f"ahead in the queue)")
            return {"stdout": "", "stderr": msg, "exitCode": 124, **base}
        if outcome == "run-timeout":
            return {"stdout": "", "stderr": f"Execution timed out after {timeout_ms}ms "
                                            f"(worker terminated and affinity worker replaced)",
                    "exitCode": 124, **base}
        return {"stdout": "", "stderr": "Worker process died during execution; the request was not re-run.",
                "exitCode": 1, **base}

    def execute_script(
        self,
        script_rel_path: str,
        payload: Any,
        args: Optional[list] = None,
        timeout_ms: int = 15000,
    ) -> Dict[str, Any]:
        """
        Executes a script concurrently in a worker process, bypassing GIL constraints.
        Automatically enforces timeouts and falls back to in-process execution if needed.
        """
        start_time = time.perf_counter()
        args = args or []

        # Resolve path: allowlisted names only, contained in script_dir (no traversal).
        try:
            full_path = resolve_script_path(self.script_dir, script_rel_path)
        except IPCRequestRejected as rejected:
            result = rejected.as_result()
            result["durationMs"] = round((time.perf_counter() - start_time) * 1000.0, 2)
            result["warm"] = True
            return result

        # Prepare JSON input string
        if payload is not None:
            input_str = payload if isinstance(payload, str) else json.dumps(payload)
        else:
            input_str = ""

        timeout_sec = max(1.0, float(timeout_ms) / 1000.0)

        affinity = self._affinity_name(full_path)
        if affinity and _payload_field(payload, "action") in METADATA_ACTIONS:
            affinity = None  # metadata (database list, coverage) never waits behind a calculation
        if affinity:
            return self._execute_affinity(affinity, full_path, input_str, args, timeout_ms, timeout_sec,
                                          payload, start_time)

        with self.stats_lock:
            self.active_jobs += 1

        try:
            # 1. Primary execution via ProcessPoolExecutor
            future = None
            if self.pool is not None:
                try:
                    future = self.pool.submit(_worker_run_script, full_path, input_str, args)
                except (BrokenProcessPool, RuntimeError):
                    # Not submitted, so not executed: recycle and use the in-process path below.
                    sys.stderr.write("[PersistentIPC] Worker pool unusable at submit; recycling...\n")
                    self._init_pool()
                    future = None
            if future is not None:
                try:
                    res = future.result(timeout=timeout_sec)
                    duration_ms = round((time.perf_counter() - start_time) * 1000.0, 2)
                    with self.stats_lock:
                        self.request_count += 1
                        self.total_duration_ms += duration_ms
                    return {
                        "stdout": res["stdout"],
                        "stderr": res["stderr"],
                        "exitCode": res["exitCode"],
                        "durationMs": duration_ms,
                        "warm": True,
                        "concurrency": "process_pool",
                    }
                except TimeoutError:
                    outcome = self._abandon(future)
                    return {
                        "stdout": "",
                        "stderr": f"Execution timed out after {timeout_ms}ms ({outcome})",
                        "exitCode": 124,
                        "durationMs": round((time.perf_counter() - start_time) * 1000.0, 2),
                        "warm": True,
                        "concurrency": "process_pool",
                    }
                except BrokenProcessPool:
                    # The worker died while this job may have been running: never re-run it here.
                    sys.stderr.write("[PersistentIPC] Worker died during execution; recycling pool...\n")
                    self._init_pool()
                    return {
                        "stdout": "",
                        "stderr": "Worker process died during execution; the request was not re-run.",
                        "exitCode": 1,
                        "durationMs": round((time.perf_counter() - start_time) * 1000.0, 2),
                        "warm": True,
                        "concurrency": "process_pool",
                    }

            # 2. Resilient In-Process Fallback if pool is recovering
            with self.fallback_lock:
                compiled = self.compiled_code.get(full_path)
                if not compiled:
                    with open(full_path, "r", encoding="utf-8") as f:
                        compiled = compile(f.read(), full_path, "exec")
                    self.compiled_code[full_path] = compiled

                old_stdin = sys.stdin
                old_stdout = sys.stdout
                old_stderr = sys.stderr
                old_argv = sys.argv

                captured_stdout = io.StringIO()
                captured_stderr = io.StringIO()
                sys.stdin = io.StringIO(input_str)
                sys.stdout = captured_stdout
                sys.stderr = captured_stderr
                sys.argv = [os.path.basename(full_path)] + args

                env = {
                    "__name__": "__main__",
                    "__file__": full_path,
                    "__package__": None,
                }

                exit_code = 0
                try:
                    exec(compiled, env)
                except SystemExit as se:
                    exit_code = se.code if isinstance(se.code, int) else 0
                except Exception:
                    exit_code = 1
                    captured_stderr.write(traceback.format_exc())
                finally:
                    sys.stdin = old_stdin
                    sys.stdout = old_stdout
                    sys.stderr = old_stderr
                    sys.argv = old_argv

                duration_ms = round((time.perf_counter() - start_time) * 1000.0, 2)
                with self.stats_lock:
                    self.request_count += 1
                    self.total_duration_ms += duration_ms

                return {
                    "stdout": captured_stdout.getvalue(),
                    "stderr": captured_stderr.getvalue(),
                    "exitCode": exit_code,
                    "durationMs": duration_ms,
                    "warm": True,
                    "concurrency": "in_process_fallback",
                }
        finally:
            with self.stats_lock:
                self.active_jobs = max(0, self.active_jobs - 1)

    def get_status(self) -> Dict[str, Any]:
        with self.stats_lock:
            req_count = self.request_count
            tot_duration = self.total_duration_ms
            active_jobs = self.active_jobs

        uptime_sec = round(time.time() - self.start_time, 1)
        avg_latency = round(tot_duration / max(1, req_count), 2) if req_count > 0 else 0.0

        return {
            "status": "online",
            "concurrencyModel": "ProcessPoolExecutor",
            "workerCount": self.num_workers,
            "activeJobs": active_jobs,
            "ipcChannels": dict(getattr(self, "channels", {})),
            "warmModules": list(self.modules.keys()),
            "compiledScripts": len(self.compiled_code),
            "requestsProcessed": req_count,
            "avgDurationMs": avg_latency,
            "uptimeSeconds": uptime_sec,
            "pythonVersion": sys.version.split()[0],
            "moduleImportTimesMs": self.import_times,
            "affinityPools": sorted(self.affinity_lanes.keys()),
            "affinityLanes": {name: lane.snapshot() for name, lane in sorted(self.affinity_lanes.items())},
        }

    def _terminate_workers(self):
        """Stops the pool and kills its worker processes (a running job cannot be cancelled)."""
        pool, self.pool = self.pool, None
        if pool is None:
            return
        procs = list((getattr(pool, "_processes", None) or {}).values())
        try:
            pool.shutdown(wait=False, cancel_futures=True)
        except Exception:
            pass
        for proc in procs:
            try:
                proc.terminate()
            except Exception:
                pass

    def _abandon(self, future) -> str:
        """After a timeout: cancel the job if it has not started; otherwise kill and recycle the
        workers when no other job is in flight, else leave it running (reported, not hidden)."""
        if future.cancel():
            return "job cancelled before it started"
        with self.stats_lock:
            others = self.active_jobs - 1
        if others <= 0:
            self._terminate_workers()
            self._init_pool()
            return "worker terminated and pool recycled"
        return f"job left running: {others} other job(s) share the pool"

    def prewarm_pool(self, timeout_s: float = 300.0) -> int:
        """Starts every worker before the service announces readiness; returns the number of distinct workers seen.

        One batch of N short tasks does not guarantee N distinct workers: under load a fast worker can drain two
        tasks before the next process has initialised. Batches are repeated until N distinct PIDs have answered,
        bounded by timeout_s; at the deadline the (smaller) observed count is returned, never an inflated one.
        """
        if self.pool is None:
            return 0
        try:
            deadline = time.monotonic() + timeout_s
            pids = set()
            while len(pids) < self.num_workers:
                futures = [self.pool.submit(_worker_noop, 0.2) for _ in range(self.num_workers)]
                for f in futures:
                    pids.add(f.result(timeout=max(0.001, deadline - time.monotonic())))
                if time.monotonic() >= deadline:
                    break
            return len(pids)
        except Exception as e:
            sys.stderr.write(f"[PersistentIPC] Worker pre-warm failed: {e}\n")
            return 0

    def shutdown(self):
        """Closes the worker pools and terminates their processes (no orphaned workers)."""
        self._terminate_workers()
        with self.affinity_lock:
            lanes, self.affinity_lanes = list(self.affinity_lanes.values()), {}
        for lane in lanes:
            lane.shutdown()


def _is_pool_worker_process() -> bool:
    """True inside a pool worker or the forkserver, where this module is re-imported.

    While a spawn/forkserver child re-imports the main script (as ``__mp_main__``),
    ``multiprocessing.parent_process()`` is still None, so the module name and the
    ``_inheriting`` flag are what identify that import; parent_process() covers the later
    by-name import when a worker unpickles ``_worker_init``.
    """
    return (__name__ == "__mp_main__"
            or bool(getattr(multiprocessing.current_process(), "_inheriting", False))
            or multiprocessing.parent_process() is not None)


# Global registry. Built at import for library use (tests, tools); when this file runs as the
# service it is built in run_services after the startup checks, so a refused launch never warms
# up; pool workers never build one (the warm-up runs exactly once per daemon).
registry: Optional[ConcurrentModuleRegistry] = (
    None if (__name__ == "__main__" or _is_pool_worker_process()) else ConcurrentModuleRegistry(SCRIPT_DIR))
WarmModuleRegistry = ConcurrentModuleRegistry

CONNECTION_IDLE_TIMEOUT_S = 60   # per socket operation once authenticated
PREAUTH_DEADLINE_S = 10          # whole request head, from accept to verified MAC
BODY_DEADLINE_S = 120            # whole authenticated body
PREAUTH_SLOTS = 8                # concurrent not-yet-authenticated connections per channel
MAX_HEAD_BYTES = 4096            # UNIX frame head line


def create_socket_path(explicit: Optional[str]) -> Tuple[str, Optional[str]]:
    """Returns (socket path, private directory to remove on stop or None).

    Without an explicit path a fresh 0700 directory is made (under XDG_RUNTIME_DIR when set), so
    no other local user can pre-create, replace or connect to the socket. An explicit path must
    sit in a directory owned by this user that is not group/world-writable (not /tmp itself).
    """
    if explicit:
        parent = os.path.dirname(os.path.abspath(explicit))
        st = os.stat(parent)
        foreign = hasattr(os, "getuid") and st.st_uid != os.getuid()
        if foreign or stat.S_IMODE(st.st_mode) & 0o022:
            raise SystemExit(
                f"[PersistentIPC] Refusing METALLIX_IPC_SOCK={explicit!r}: its directory must be owned by "
                "this user and not group/world-writable. Unset it to get a private 0700 directory.")
        return explicit, None
    base = os.environ.get("XDG_RUNTIME_DIR")
    private_dir = tempfile.mkdtemp(prefix="metallix-ipc-", dir=base if base and os.path.isdir(base) else None)
    os.chmod(private_dir, 0o700)
    return os.path.join(private_dir, "ipc.sock"), private_dir


def _frame(status: int, body_obj: Any, token: Optional[str], nonce: Optional[str]) -> bytes:
    body = json.dumps(body_obj).encode("utf-8")
    digest = body_digest(body)
    head: Dict[str, Any] = {"v": 2, "status": int(status), "len": len(body), "sha256": digest}
    if nonce is not None and token:
        head["mac"] = response_mac(token, nonce, status, len(body), digest)
    return json.dumps(head).encode("utf-8") + b"\n" + body


# =========================================================================
# 1. UNIX Domain Socket IPC Server (one framed request per connection)
# =========================================================================
# Request:  head line {"v": 2, "ts", "nonce", "len", "sha256", "mac"} + "\n" + exactly len body bytes
#           mac = request_mac(token, "UNIX", "/", ts, nonce, len, sha256), verified before the body.
# Response: head line {"v": 2, "status", "len", "sha256", "mac"} + "\n" + body.
#           status 200 = executed (any exitCode); >= 400 = refused before execution. Only responses
#           to authenticated requests are signed.
class UnixIPCServer:
    def __init__(self, sock_path: str, reg: ConcurrentModuleRegistry, token: Optional[str] = None,
                 private_dir: Optional[str] = None):
        self.sock_path = sock_path
        self.private_dir = private_dir
        self.reg = reg
        self.token = token
        self.nonces = NonceCache()
        self.preauth = threading.BoundedSemaphore(PREAUTH_SLOTS)
        self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.running = False
        self.thread = None

    def bind(self):
        """Creates the owner-only socket and listens; connections wait until serve()."""
        if self.private_dir is None and os.path.lexists(self.sock_path):
            os.remove(self.sock_path)  # explicit path in a private directory: a stale socket of ours

        # Owner-only from creation (umask) and explicitly afterwards; never world-writable.
        old_umask = os.umask(0o177)
        try:
            self.sock.bind(self.sock_path)
        finally:
            os.umask(old_umask)
        os.chmod(self.sock_path, 0o600)
        self.sock.listen(64)

    def serve(self):
        self.running = True
        self.thread = threading.Thread(target=self._accept_loop, daemon=True)
        self.thread.start()
        sys.stderr.write(f"[PersistentIPC] UNIX domain socket listening at {self.sock_path}\n")

    def start(self):
        self.bind()
        self.serve()

    def _accept_loop(self):
        while self.running:
            try:
                conn, _ = self.sock.accept()
                threading.Thread(target=self._handle_client, args=(conn,), daemon=True).start()
            except Exception:
                if not self.running:
                    break

    @staticmethod
    def _read_head(conn: socket.socket, deadline: float) -> Tuple[bytes, bytes]:
        """Reads the head line (bounded, newline searched only in new data)."""
        buf = bytearray()
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise IPCRequestRejected(408, "REQUEST_TIMEOUT", "IPC request head not received in time")
            conn.settimeout(remaining)
            try:
                chunk = conn.recv(4096)
            except socket.timeout:
                raise IPCRequestRejected(408, "REQUEST_TIMEOUT", "IPC request head not received in time")
            if not chunk:
                raise IPCRequestRejected(400, "INVALID_FRAME", "Connection closed before the request head")
            start = len(buf)
            buf += chunk
            i = buf.find(b"\n", start)
            if i >= 0:
                return bytes(buf[:i]), bytes(buf[i + 1:])
            if len(buf) > MAX_HEAD_BYTES:
                raise IPCRequestRejected(413, "HEAD_TOO_LARGE", "IPC request head too large")

    def _handle_client(self, conn: socket.socket):
        if not self.preauth.acquire(blocking=False):
            conn.close()  # too many unauthenticated connections
            return
        holding = True
        nonce = None
        try:
            try:
                head_line, rest = self._read_head(conn, time.monotonic() + PREAUTH_DEADLINE_S)
                try:
                    head = json.loads(head_line.decode("utf-8"))
                except Exception:
                    raise IPCRequestRejected(400, "INVALID_FRAME", "Invalid IPC frame head")
                if not isinstance(head, dict) or head.get("v") != 2:
                    raise IPCRequestRejected(401, "UNAUTHORIZED", "Missing or malformed IPC authentication")
                length = head.get("len")
                if isinstance(length, bool) or not isinstance(length, int) or length <= 0:
                    raise IPCRequestRejected(400, "INVALID_FRAME", "Invalid IPC frame length")
                if length > MAX_BODY_BYTES:
                    raise IPCRequestRejected(413, "PAYLOAD_TOO_LARGE", f"Body larger than {MAX_BODY_BYTES} bytes")
                verify_request(self.token, "UNIX", "/", head.get("ts"), head.get("nonce"), head.get("mac"),
                               length, head.get("sha256"), self.nonces)
                nonce = head["nonce"]
                self.preauth.release()
                holding = False

                pending = [rest]

                def read(n: int) -> bytes:
                    if pending[0]:
                        part, pending[0] = pending[0][:n], pending[0][n:]
                        return part
                    return conn.recv(n)

                conn.settimeout(CONNECTION_IDLE_TIMEOUT_S)
                body = read_body_checked(read, length, head["sha256"], time.monotonic() + BODY_DEADLINE_S)
                try:
                    req = json.loads(body.decode("utf-8"))
                except Exception:
                    req = None
                if not isinstance(req, dict):
                    raise IPCRequestRejected(400, "INVALID_REQUEST", "Request body must be a JSON object")
            except IPCRequestRejected as rejected:
                conn.sendall(_frame(rejected.status, {"error": rejected.message, "code": rejected.code},
                                    self.token, nonce))
                return

            action = req.get("action", "execute")
            req_id = req.get("id")
            if action == "status":
                result = self.reg.get_status()
            elif action == "ping":
                result = {"pong": True}
            else:
                try:
                    script, payload, args, timeout_ms = validate_exec_request(req)
                    resolve_script_path(self.reg.script_dir, script)
                except IPCRequestRejected as rejected:
                    result = {"error": rejected.message, "code": rejected.code}
                    if req_id is not None:
                        result["id"] = req_id
                    conn.sendall(_frame(rejected.status, result, self.token, nonce))
                    return
                result = self.reg.execute_script(script, payload, args, timeout_ms)
            if req_id is not None:
                result["id"] = req_id
            conn.sendall(_frame(200, result, self.token, nonce))
        except (ConnectionResetError, BrokenPipeError, socket.timeout):
            pass
        except Exception as e:
            sys.stderr.write(f"[PersistentIPC] Client connection error: {e}\n")
        finally:
            if holding:
                self.preauth.release()
            try:
                conn.close()
            except Exception:
                pass

    def stop(self):
        self.running = False
        try:
            self.sock.close()
        except Exception:
            pass
        if os.path.lexists(self.sock_path):
            try:
                os.remove(self.sock_path)
            except OSError:
                pass
        if self.private_dir:
            shutil.rmtree(self.private_dir, ignore_errors=True)


# =========================================================================
# 2. Loopback HTTP Microservice (ephemeral port; Windows, or POSIX with METALLIX_IPC_HTTP=1)
# =========================================================================
class MicroserviceHTTPHandler(http.server.BaseHTTPRequestHandler):
    """Loopback REST handler. No CORS: browsers are not clients of this service.

    Security configuration lives on the server object (see ThreadedHTTPServer): ``ipc_token``,
    ``allowed_hosts``, ``nonces``, ``preauth`` and ``registry``. One request per connection.
    Requests carry X-Metallix-Ts / -Nonce / -Body-Sha256 / -Mac; the MAC covers method, path, ts,
    nonce, Content-Length and the body hash and is verified before the body is read. Responses
    carry X-Metallix-Body-Sha256 and, for authenticated requests, X-Metallix-Mac.
    """

    timeout = CONNECTION_IDLE_TIMEOUT_S  # per socket operation
    _MAX_DRAIN_BYTES = 64 * 1024

    def log_message(self, format, *args):
        # Silence default access log to keep stdout/stderr clean
        pass

    @property
    def _registry(self) -> "ConcurrentModuleRegistry":
        return getattr(self.server, "registry", None) or registry

    def handle(self):
        """One request per connection, inside a bounded, time-boxed pre-authentication slot."""
        self._auth_nonce = None
        self._body_read = False
        self._sem = getattr(self.server, "preauth", None)
        if self._sem is not None and not self._sem.acquire(blocking=False):
            self._sem = None
            return  # too many unauthenticated connections: close without reading
        self._preauth_open = True
        self._timer = threading.Timer(PREAUTH_DEADLINE_S, self._abort_unauthenticated)
        self._timer.daemon = True
        self._timer.start()
        try:
            self.close_connection = True
            self.handle_one_request()
        except (OSError, ValueError):
            pass  # client went away, or the pre-auth deadline cut the connection
        finally:
            self._end_preauth()

    def _abort_unauthenticated(self):
        if getattr(self, "_preauth_open", False):
            try:
                self.connection.shutdown(socket.SHUT_RDWR)
            except OSError:
                pass

    def _end_preauth(self):
        if getattr(self, "_preauth_open", False):
            self._preauth_open = False
            self._timer.cancel()
            if self._sem is not None:
                self._sem.release()

    def _send_json(self, status_code: int, data: Any):
        body = json.dumps(data).encode("utf-8")
        digest = body_digest(body)
        self.send_response(status_code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("Connection", "close")
        self.send_header("X-Metallix-Body-Sha256", digest)
        nonce = getattr(self, "_auth_nonce", None)
        token = getattr(self.server, "ipc_token", None)
        if nonce and token:
            self.send_header("X-Metallix-Mac", response_mac(token, nonce, status_code, len(body), digest))
        self.end_headers()
        self.wfile.write(body)

    def _reject(self, rejected: IPCRequestRejected):
        # Drain a small unread body first: closing a socket with unread data makes some
        # stacks (Windows) reset the connection before the client reads the error.
        if self.command == "POST" and not self._body_read:
            try:
                pending = int(self.headers.get("Content-Length", 0))
            except ValueError:
                pending = 0
            if 0 < pending <= self._MAX_DRAIN_BYTES:
                try:
                    self.rfile.read(pending)
                except OSError:
                    pass
        self.close_connection = True
        self._send_json(rejected.status, {"error": rejected.message, "code": rejected.code})

    def _authenticate(self, require_json: bool) -> bytes:
        """Head checks and MAC verification (no body byte read), then the hash-checked body."""
        ts, nonce, mac, digest = check_http_headers(
            self.headers, allowed_hosts=getattr(self.server, "allowed_hosts", frozenset()),
            require_json=require_json)
        raw_length = self.headers.get_all("Content-Length") or []
        try:
            length = int(raw_length[0]) if len(raw_length) == 1 else (0 if not raw_length else -1)
        except ValueError:
            length = -1
        if length < 0 or (self.command == "POST" and length == 0) or (self.command != "POST" and length != 0):
            raise IPCRequestRejected(400, "INVALID_LENGTH", "Missing or invalid Content-Length")
        if length > MAX_BODY_BYTES:
            raise IPCRequestRejected(413, "PAYLOAD_TOO_LARGE", f"Body larger than {MAX_BODY_BYTES} bytes")
        verify_request(getattr(self.server, "ipc_token", None), self.command, self.path, ts, nonce, mac,
                       length, digest, self.server.nonces)
        self._auth_nonce = nonce
        self._end_preauth()
        body = read_body_checked(self.rfile.read, length, digest, time.monotonic() + BODY_DEADLINE_S)
        self._body_read = True
        return body

    def do_GET(self):
        try:
            self._authenticate(require_json=False)
        except IPCRequestRejected as rejected:
            return self._reject(rejected)
        if self.path in ["/status", "/health", "/api/status", "/api/health"]:
            self._send_json(200, self._registry.get_status())
        elif self.path == "/ping":
            self._send_json(200, {"pong": True, "timestamp": time.time()})
        else:
            self._send_json(404, {"error": "Endpoint not found", "path": self.path})

    def do_POST(self):
        try:
            body_bytes = self._authenticate(require_json=True)
        except IPCRequestRejected as rejected:
            return self._reject(rejected)
        if self.path in ["/execute", "/run", "/api/execute", "/api/run"]:
            try:
                req = json.loads(body_bytes.decode("utf-8"))
            except Exception as e:
                return self._reject(IPCRequestRejected(400, "INVALID_JSON", f"JSON parse error: {str(e)}"))

            try:
                script, payload, args, timeout_ms = validate_exec_request(req)
                resolve_script_path(self._registry.script_dir, script)
            except IPCRequestRejected as rejected:
                return self._reject(rejected)

            result = self._registry.execute_script(script, payload, args, timeout_ms)
            if "id" in req:
                result["id"] = req["id"]
            self._send_json(200, result)

        elif self.path == "/warmup":
            self._registry.warmup()
            self._send_json(200, self._registry.get_status())
        else:
            self._send_json(404, {"error": "Endpoint not found", "path": self.path})


class ThreadedHTTPServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True
    # On Windows SO_REUSEADDR lets another process bind the same port while we hold it (port
    # stealing); bind with SO_EXCLUSIVEADDRUSE there instead. POSIX SO_REUSEADDR only allows
    # rebinding over TIME_WAIT and is kept.
    allow_reuse_address = os.name != "nt"
    ipc_token: Optional[str] = None
    allowed_hosts: frozenset = frozenset()
    registry: Optional["ConcurrentModuleRegistry"] = None
    nonces: "NonceCache"
    preauth: Optional[threading.BoundedSemaphore] = None

    def handle_error(self, request, client_address):
        # Never print request tracebacks (they could echo request data); one line is enough.
        exc = sys.exc_info()[1]
        if not isinstance(exc, OSError):
            sys.stderr.write(f"[PersistentIPC] HTTP handler error: {exc.__class__.__name__}\n")

    def server_bind(self):
        if os.name == "nt" and hasattr(socket, "SO_EXCLUSIVEADDRUSE"):
            self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_EXCLUSIVEADDRUSE, 1)
        super().server_bind()


class ThreadedHTTPServer6(ThreadedHTTPServer):
    address_family = socket.AF_INET6


def make_http_server(host: str, port: int, token: Optional[str],
                     reg: Optional["ConcurrentModuleRegistry"] = None) -> ThreadedHTTPServer:
    """Builds the HTTP service with its security configuration (port 0 picks a free port).
    IPv6 loopback (::1) gets an AF_INET6 socket."""
    bare = host.strip().strip("[]")
    cls = ThreadedHTTPServer6 if ":" in bare else ThreadedHTTPServer
    httpd = cls((bare, port), MicroserviceHTTPHandler)
    httpd.ipc_token = token
    httpd.allowed_hosts = allowed_host_headers(bare, httpd.server_address[1])
    httpd.nonces = NonceCache()
    httpd.preauth = threading.BoundedSemaphore(PREAUTH_SLOTS)
    httpd.registry = reg
    return httpd


def _http_url(host: str, port: int) -> str:
    h = host.strip("[]")
    return f"http://[{h}]:{port}" if ":" in h else f"http://{h}:{port}"


def _detach_stdin_for_watch() -> None:
    """Moves the supervisor's stdin pipe off fd 0 before any worker process exists.

    On Windows a ``spawn`` child does not finish starting while another thread of its parent holds
    a pending synchronous read on the inherited stdin pipe (the stdin watch thread): the worker
    hangs at interpreter start (review B1: the CALPHAD affinity worker, started after the watch
    thread, never ran a job; a shared-pool recycle during the watch hung the same way). The pipe
    is kept on a duplicated, non-inheritable descriptor that becomes sys.stdin for the watcher;
    fd 0, which children inherit, is pointed at the null device. EOF detection is unchanged.
    """
    try:
        keep = os.dup(0)  # non-inheritable by default (PEP 446)
    except OSError:
        return  # no stdin to watch or to hand down
    null = os.open(os.devnull, os.O_RDONLY)
    try:
        os.dup2(null, 0)
    finally:
        os.close(null)
    sys.stdin = os.fdopen(keep, "r", encoding="utf-8", errors="replace")


def _watch_stdin_eof(on_eof) -> None:
    """Calls on_eof() when stdin reaches EOF (the supervisor that holds the pipe is gone)."""
    def run():
        try:
            stream = sys.stdin.buffer if sys.stdin is not None else None
            while stream is not None and stream.read(65536):
                pass
        except Exception:
            pass
        on_eof()

    threading.Thread(target=run, daemon=True, name="metallix-ipc-stdin-watch").start()


def run_services():
    """Checks the configuration and binds the channels before any warm-up, then serves."""
    global registry
    token = _take_ipc_token()
    validate_startup_config(HTTP_HOST, token)

    # 1. UNIX domain socket IPC (POSIX). Failure is fatal: the supervisor must not believe in a
    #    channel that does not exist, and a silent HTTP-only fallback hides a hostile /tmp.
    ipc_server = None
    if os.name != "nt":
        try:
            sock_path, private_dir = create_socket_path(UNIX_SOCKET_PATH)
            ipc_server = UnixIPCServer(sock_path, None, token, private_dir)
            ipc_server.bind()
        except (OSError, SystemExit) as e:
            if ipc_server is not None:
                ipc_server.stop()
            raise SystemExit(e.code if isinstance(e, SystemExit) else
                             f"[PersistentIPC] Refusing to start: UNIX socket unavailable ({e}).")
    else:
        sys.stderr.write("[PersistentIPC] UNIX socket skipped on Windows; HTTP loopback only.\n")

    # 2. HTTP microservice (Windows always; POSIX with METALLIX_IPC_HTTP=1). Ephemeral port unless
    #    METALLIX_IPC_PORT is set; exclusive bind on Windows; fatal when it is the only channel.
    #    A failed fixed port is reported as inactive, so the supervisor never talks to its holder.
    httpd = None
    if HTTP_ENABLED:
        try:
            httpd = make_http_server(HTTP_HOST, HTTP_PORT, token, None)
        except OSError as e:
            sys.stderr.write(f"[PersistentIPC] HTTP microservice bind error on {HTTP_HOST}:{HTTP_PORT}: {e}\n")
            if ipc_server is None:
                raise SystemExit(f"[PersistentIPC] Refusing to start: no IPC channel could be opened ({e}).")
    del token

    # 3. Warm-up and worker pool only once the channels are ours; workers are started and warmed
    #    before the ready message, so the first request does not pay for them. The stdin pipe is
    #    moved off fd 0 first (B1), so no worker, now or after a recycle, inherits it.
    if STDIN_WATCH:
        _detach_stdin_for_watch()
    if registry is None:
        registry = ConcurrentModuleRegistry(SCRIPT_DIR)
    workers_ready = registry.prewarm_pool()
    registry.start_affinity_pools()
    if ipc_server:
        ipc_server.reg = registry
        ipc_server.serve()
    if httpd:
        httpd.registry = registry

    http_port = httpd.server_address[1] if httpd else None
    http_url = _http_url(HTTP_HOST, http_port) if httpd else None
    if httpd:
        sys.stderr.write(f"[PersistentIPC] HTTP microservice listening at {http_url}\n")
    registry.channels = {"unixSocket": ipc_server.sock_path if ipc_server else None, "httpMicroservice": http_url}

    shutting_down = threading.Lock()

    def shutdown_and_exit(reason: str, code: int = 0):
        if not shutting_down.acquire(blocking=False):
            return
        sys.stderr.write(f"\n[PersistentIPC] {reason}; shutting down cleanly...\n")
        if ipc_server:
            ipc_server.stop()
        registry.shutdown()
        os._exit(code)

    def handle_signal(sig, frame):
        shutdown_and_exit(f"Received signal {sig}")

    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)
    if STDIN_WATCH:
        _watch_stdin_eof(lambda: shutdown_and_exit("Supervisor gone (stdin closed)"))

    # Inform the supervisor on stdout which channels are really ours and where they are.
    ready_msg = {
        "status": "ready",
        "unixSocket": ipc_server.sock_path if ipc_server else None,
        "http": http_url,
        "httpHost": HTTP_HOST if httpd else None,
        "httpPort": http_port,
        "protocol": PROTOCOL.decode("ascii"),
        "modulesWarm": len(registry.modules),
        "warmModules": list(registry.modules.keys()),
        "pythonVersion": sys.version.split()[0],
        "unixSocketActive": ipc_server is not None,
        "httpActive": httpd is not None,
        "workers": registry.num_workers,
        "workersStarted": workers_ready,
        "concurrency": "ProcessPoolExecutor",
    }
    sys.stdout.write(json.dumps(ready_msg) + "\n")
    sys.stdout.flush()

    try:
        if httpd:
            httpd.serve_forever()
        else:
            while True:
                time.sleep(1)
    finally:
        if ipc_server:
            ipc_server.stop()


if __name__ == "__main__":
    run_services()
