"""
Phase 9: AI Surrogate Model (Physics-Informed Neural Network / RF Proxy)
Trains on synthetic data generated by the Phase 7 GPU/Analytical solvers.
Includes Out-of-Distribution (OOD) detection via ensemble variance (Error Budget).
"""
import os
import json
import time
import numpy as np
from pathlib import Path
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
import joblib

from lpbf_thermal_solver import calculate_meltpool_physics
from alloy_data_kinetics_uq_fatigue import process_map_material_name

SURROGATE_DIR = Path(".lpbf-surrogates")
SURROGATE_DIR.mkdir(parents=True, exist_ok=True)

def _get_model_path(alloy_name: str) -> Path:
    return SURROGATE_DIR / f"{alloy_name.lower().replace(' ', '_')}_rf_model.pkl"

def generate_synthetic_data(alloy_name: str, num_samples: int = 100):
    """Generates training data using the baseline physical solver."""
    import pandas as pd
    
    print(f"[{alloy_name}] Generating {num_samples} dynamic synthetic data points (varying T0)...")
    data = []
    
    # 1. Generate dynamic points (for T0 sensitivity)
    p_range = (100, 500)
    v_range = (400, 2000)
    t_preheat_range = (25, 200)
    
    np.random.seed(42) # Reproducibility
    for i in range(num_samples):
        P = np.random.uniform(*p_range)
        V = np.random.uniform(*v_range)
        T0 = np.random.uniform(*t_preheat_range)
        
        try:
            res = calculate_meltpool_physics(
                material_name=alloy_name,
                laser_power_W=P,
                scan_speed_mm_s=V,
                beam_diameter_um=80.0,
                layer_thickness_um=30.0,
                preheat_temp_C=T0,
                heat_source="rosenthal" # We use standard baseline for fast dataset generation
            )
            
            geom = res.get("meltPoolGeometry", {})
            w = geom.get("width_um", 0)
            d = geom.get("depth_um", 0)
            l = geom.get("length_um", 0)
            if w > 0 and d > 0:
                data.append({
                    "P": P, "V": V, "T0": T0,
                    "W": w, "D": d, "L": l
                })
        except Exception as e:
            # print(f"Error for P={P}, V={V}: {e}")
            continue
            
    # 2. Load comprehensive dataset points (Phase 15 / ML Data generation)
    csv_path = Path("../data/synthetic_process_map.csv")
    if csv_path.exists():
        print(f"[{alloy_name}] Loading comprehensive data from {csv_path}...")
        df = pd.read_csv(csv_path)
        # Map nomenclature if necessary (only "IN718" is renamed; Phase 6a moved the table)
        query_mat = process_map_material_name(alloy_name)
        df_alloy = df[df["Material"] == query_mat]
        
        if not df_alloy.empty:
            # We only need unique P, V combinations for the meltpool geometries
            df_unique = df_alloy.drop_duplicates(subset=["Power_W", "Speed_mm_s"])
            for _, row in df_unique.iterrows():
                data.append({
                    "P": row["Power_W"],
                    "V": row["Speed_mm_s"],
                    "T0": 25.0, # Dataset used T0=25.0
                    "W": row["Width_um"],
                    "D": row["Depth_um"],
                    "L": row["Length_um"]
                })
            print(f"[{alloy_name}] Added {len(df_unique)} dense points from comprehensive process map.")

    print(f"[{alloy_name}] Successfully aggregated {len(data)} valid points.")
    return data

def train_surrogate(alloy_name: str, num_samples: int = 200):
    """Trains a Random Forest Surrogate Model with Error Budgeting (OOD detection)."""
    data = generate_synthetic_data(alloy_name, num_samples)
    if len(data) < 10:
        raise ValueError("Not enough data to train surrogate.")
        
    X = np.array([[d["P"], d["V"], d["T0"]] for d in data])
    y = np.array([[d["W"], d["D"], d["L"]] for d in data])
    
    scaler_x = StandardScaler()
    X_scaled = scaler_x.fit_transform(X)
    
    # We use RF because variance across trees gives us an excellent Out-of-Distribution (OOD) measure
    # which is required by Phase 9 "Grup bazlı ayrılmış değerlendirme, alan dışı davranış ve hata bütçesi"
    rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
    rf.fit(X_scaled, y)
    
    # Save model and scaler
    model_payload = {
        "model": rf,
        "scaler": scaler_x,
        "training_bounds": {
            "P": [X[:, 0].min(), X[:, 0].max()],
            "V": [X[:, 1].min(), X[:, 1].max()],
            "T0": [X[:, 2].min(), X[:, 2].max()]
        }
    }
    
    path = _get_model_path(alloy_name)
    joblib.dump(model_payload, path)
    print(f"[{alloy_name}] Surrogate model saved to {path}.")
    return path

def predict_surrogate(alloy_name: str, P: float, V: float, T0: float):
    """
    Real-time milliseconds prediction.
    Returns the predictions AND the OOD error budget (variance across trees).
    """
    path = _get_model_path(alloy_name)
    if not path.exists():
        raise FileNotFoundError(f"Surrogate model for {alloy_name} not found. Please train first.")
        
    payload = joblib.load(path)
    model = payload["model"]
    scaler = payload["scaler"]
    bounds = payload["training_bounds"]
    
    # OOD Check (Error budget increases if we are outside the training bounds)
    is_ood = False
    if not (bounds["P"][0] <= P <= bounds["P"][1]) or \
       not (bounds["V"][0] <= V <= bounds["V"][1]) or \
       not (bounds["T0"][0] <= T0 <= bounds["T0"][1]):
        is_ood = True
        
    X_input = np.array([[P, V, T0]])
    X_scaled = scaler.transform(X_input)
    
    # Predict using all trees to get mean and variance (Error Budget)
    preds = np.array([tree.predict(X_scaled)[0] for tree in model.estimators_])
    mean_pred = preds.mean(axis=0)
    std_pred = preds.std(axis=0)
    
    # Width, Depth, Length
    return {
        "surrogate_used": True,
        "width_um": float(mean_pred[0]),
        "depth_um": float(mean_pred[1]),
        "length_um": float(mean_pred[2]),
        "error_budget": {
            "is_out_of_distribution": is_ood,
            "width_std_um": float(std_pred[0]),
            "depth_std_um": float(std_pred[1]),
            "confidence_pct": float(100.0 / (1.0 + (std_pred[0]/max(mean_pred[0], 1.0)))) if not is_ood else 0.0
        },
        "computeTimeMs": 1.0 # Instant
    }

if __name__ == "__main__":
    # Test execution
    train_surrogate("IN718", 200)
    res = predict_surrogate("IN718", 250, 1000, 25)
    print("Test Prediction (In-Distribution):", json.dumps(res, indent=2))
    
    res_ood = predict_surrogate("IN718", 1000, 50, 500) # Extreme OOD
    print("Test Prediction (Out-of-Distribution):", json.dumps(res_ood, indent=2))
