"""Emit src/generated/lpbfMaterialAuthority.json from the Python LPBF material authority.

The TypeScript side must not hold its own alloy numbers. This script projects
python/four_alloy_materials.py (four_alloy_thermophysical_db(), LITERATURE_PV_WINDOWS,
canonical_material_source()) and the evidence label that python/lpbf_material_registry.py
attaches to those values into one committed JSON file that the UI reads.
IN625 is not one of the four locked alloys: its constant-property row is projected from
python/lpbf_thermal_solver.py SECONDARY_THERMOPHYSICAL_DB (the table the Rosenthal path
uses) and labelled as such. Nothing here computes, rounds or fills in a value.

Usage (from the repo root, with the locked interpreter):
    python -B scripts/emit-lpbf-material-authority.py           # write the generated file
    python -B scripts/emit-lpbf-material-authority.py --check   # exit 1 when out of date
Equality tests: python/test_lpbf_material_authority_json.py, tests/lpbf-material-authority.test.ts.
"""
import json
import sys
from pathlib import Path

sys.dont_write_bytecode = True
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "python"))

import four_alloy_materials as fam  # noqa: E402
import lpbf_material_registry as registry  # noqa: E402
from lpbf_thermal_solver import SECONDARY_THERMOPHYSICAL_DB  # noqa: E402

GENERATED_JSON = REPO_ROOT / "src" / "generated" / "lpbfMaterialAuthority.json"
SCHEMA_VERSION = 1
IN625_THERMAL_NAME = "Inconel 625"
IN625_NOTE = (
    "Secondary alloy, outside the four-alloy authority. Constant properties are "
    "python/lpbf_thermal_solver.py SECONDARY_THERMOPHYSICAL_DB['Inconel 625'] (Rosenthal / build-job path). "
    "python/in625_thermal_material.py holds a separate IN625 thermal model (Sabau et al. 2020; "
    "latent heat 290 kJ/kg there, 260 kJ/kg here); the two are not reconciled."
)


def build_document():
    db = fam.four_alloy_thermophysical_db()
    alloys = {}
    for aid in fam.FOUR_ALLOY_IDS:
        name = fam.THERMAL_NAME[aid]
        evidence = registry.material(name)
        _snapshot, source_sha256 = fam.canonical_material_source(aid)
        alloys[aid] = {
            "thermalName": name,
            "slicerName": fam.SLICER_NAME[aid],
            "quality": evidence["quality"],
            "source": evidence["source"],
            "canonicalSourceSha256": source_sha256,
            "thermal": dict(db[name]),
            "literaturePvWindow": dict(fam.LITERATURE_PV_WINDOWS[aid]),
        }
    return {
        "_generated": "GENERATED by scripts/emit-lpbf-material-authority.py. Do not edit by hand.",
        "schemaVersion": SCHEMA_VERSION,
        "authority": "python/" + fam.MATERIAL_AUTHORITY,
        "authoritySchemaVersion": fam.MATERIAL_AUTHORITY_SCHEMA_VERSION,
        "alloyIds": list(fam.FOUR_ALLOY_IDS),
        "alloys": alloys,
        "secondary": {
            "in625": {
                "thermalName": IN625_THERMAL_NAME,
                "source": "python/lpbf_thermal_solver.py SECONDARY_THERMOPHYSICAL_DB",
                "note": IN625_NOTE,
                "thermal": dict(SECONDARY_THERMOPHYSICAL_DB[IN625_THERMAL_NAME]),
            },
        },
    }


def render(document=None):
    """Deterministic LF text (the file is pinned to LF in .gitattributes)."""
    document = build_document() if document is None else document
    return json.dumps(document, indent=2, ensure_ascii=False, allow_nan=False) + "\n"


def rendered_bytes():
    return render().encode("utf-8")


def is_current():
    return GENERATED_JSON.exists() and GENERATED_JSON.read_bytes() == rendered_bytes()


def main(argv):
    if "--check" in argv:
        if is_current():
            return 0
        print(f"stale: {GENERATED_JSON} (run python -B scripts/emit-lpbf-material-authority.py)", file=sys.stderr)
        return 1
    GENERATED_JSON.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_JSON.write_bytes(rendered_bytes())
    print(f"wrote {GENERATED_JSON}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
